

#include "c3.h"
#include "SoundManager.h"
#include "gamesounds.h"
#include "SoundRecord.h"

extern SoundManager	*g_soundManager;

GameSoundData g_gameSounds[] = {
	{GAMESOUNDS_SPACE_LAUNCH,		"SOUND_ID_SPACE_LAUNCH"},
	
	{GAMESOUNDS_BUILDING_STARTED,	"SOUND_ID_BUILDING_STARTED"},
	{GAMESOUNDS_BUILDING_COMPLETE,	"SOUND_ID_BUILDING_COMPLETE"},

	{GAMESOUNDS_GOODY_BOGUS,		"SOUND_ID_GOODY_BOGUS"},
	{GAMESOUNDS_GOODY_CITY,			"SOUND_ID_GOODY_CITY"},
	{GAMESOUNDS_GOODY_GOLD,			"SOUND_ID_GOODY_GOLD"},
	{GAMESOUNDS_GOODY_ADVANCE,		"SOUND_ID_GOODY_ADVANCE"},
	{GAMESOUNDS_GOODY_UNIT,			"SOUND_ID_GOODY_UNIT"},
	{GAMESOUNDS_SETTLE_CITY,		"SOUND_ID_SETTLE_CITY"},
	{GAMESOUNDS_NET_YOUR_TURN,		"SOUND_ID_NET_YOUR_TURN"},

	{GAMESOUNDS_EXPLOSION,			"SOUND_ID_EXPLOSION"},

    {GAMESOUNDS_DEFAULT_FAIL,		"SOUND_ID_DEFAULT_FAIL"}, 
    {GAMESOUNDS_DEFAULT_CLICK,      "SOUND_ID_DEFAULT_CLICK"}, 
	{GAMESOUNDS_BUTTON_PRESS,		"SOUND_ID_BUTTON_PRESS"},

	{GAMESOUNDS_CHEER_CASTLE,		"SOUND_ID_CHEER_CASTLE"},
	{GAMESOUNDS_CHEER_ENTERTAINMENT,"SOUND_ID_CHEER_ENTERTAINMENT"},
	{GAMESOUNDS_CHEER_FOUNTAIN,		"SOUND_ID_CHEER_FOUNTAIN"},
	{GAMESOUNDS_CHEER_STATUE,		"SOUND_ID_CHEER_STATUE"},
	{GAMESOUNDS_CHEER_RELIGIOUS,	"SOUND_ID_CHEER_RELIGIOUS"},

	{GAMESOUNDS_BUTTONCLICK,		"SOUND_ID_BUTTONCLICK"},
	{GAMESOUNDS_MINWINDOW,			"SOUND_ID_MINWINDOW"},
	{GAMESOUNDS_MAXWINDOW,			"SOUND_ID_MAXWINDOW"},
	{GAMESOUNDS_SLIDERUP,			"SOUND_ID_SLIDERUP"},
	{GAMESOUNDS_SLIDERDOWN,			"SOUND_ID_SLIDERDOWN"},
	{GAMESOUNDS_BOUNCEMSG,			"SOUND_ID_BOUNCEMSG"},
	{GAMESOUNDS_ALERT,				"SOUND_ID_ALERT"},
	{GAMESOUNDS_GENERALFAIL,		"SOUND_ID_GENERALFAIL"},
	{GAMESOUNDS_GENERALSUCCEED,		"SOUND_ID_GENERALSUCCEED"},

	{GAMESOUNDS_CLOAK,				"SOUND_ID_CLOAK"},
	{GAMESOUNDS_UNCLOAK,			"SOUND_ID_UNCLOAK"},
	{GAMESOUNDS_RAILLAUNCH,			"SOUND_ID_RAILLAUNCH"},

	{GAMESOUNDS_CITYCONQUERED,		"SOUND_ID_CITY_TAKEOVER"},
	{GAMESOUNDS_TOOEXPENSIVE,		"SOUND_ID_MONEY"},
	{GAMESOUNDS_DISBANDED,			"SOUND_ID_DISBANDED"},
	{GAMESOUNDS_CHAT_MESSAGE,		"SOUND_ID_CHAT_MESSAGE"},

	{GAMESOUNDS_ADVANCE, "SOUND_ID_ADVANCE"},
	{GAMESOUNDS_BOO, "SOUND_ID_BOO"},
	{GAMESOUNDS_CHANGE_GOV, "SOUND_ID_CHANGE_GOV"},
	{GAMESOUNDS_DIP_AGREE, "SOUND_ID_DIP_AGREE"},
	{GAMESOUNDS_DIP_ALERT, "SOUND_ID_DIP_ALERT"},
	{GAMESOUNDS_DIP_PEACE, "SOUND_ID_DIP_PEACE"},
	{GAMESOUNDS_DIP_WAR, "SOUND_ID_DIP_WAR"},
	{GAMESOUNDS_DISABLED, "SOUND_ID_DISABLED"},
	{GAMESOUNDS_DRAGDROP_FAIL, "SOUND_ID_DRAGDROP_FAIL"},
	{GAMESOUNDS_DRAGDROP_PASS, "SOUND_ID_DRAGDROP_PASS"},
	{GAMESOUNDS_EDIT_TEXT, "SOUND_ID_EDIT_TEXT"},
	{GAMESOUNDS_ENDTURN, "SOUND_ID_ENDTURN"},
	{GAMESOUNDS_ILLEGAL_MOVE, "SOUND_ID_ILLEGAL_MOVE"},
	{GAMESOUNDS_ILLEGAL_SPECIAL, "SOUND_ID_ILLEGAL_SPECIAL"},
	{GAMESOUNDS_LAUNCH, "SOUND_ID_LAUNCH"},
	{GAMESOUNDS_LOADING, "SOUND_ID_LOADING"},
	{GAMESOUNDS_LOSE_PLAYER_BATTLE, "SOUND_ID_LOSE_PLAYER_BATTLE"},
	{GAMESOUNDS_LOSE_PLAYER_CITY, "SOUND_ID_LOSE_PLAYER_CITY"},
	{GAMESOUNDS_MP_ALERT_TURN, "SOUND_ID_MP_ALERT_TURN"},
	{GAMESOUNDS_MP_HURRY1, "SOUND_ID_MP_HURRY1"},
	{GAMESOUNDS_MP_HURRY2, "SOUND_ID_MP_HURRY2"},
	{GAMESOUNDS_POLLUTION_ALERT, "SOUND_ID_POLLUTION_ALERT"},
	{GAMESOUNDS_POPUP, "SOUND_ID_POPUP"},
	{GAMESOUNDS_SCIFI_SCREEN, "SOUND_ID_SCIFI_SCREEN"},
	{GAMESOUNDS_SUCCESS_FANFARE, "SOUND_ID_SUCCESS_FANFARE"},
	{GAMESOUNDS_SWITCH_OFF, "SOUND_ID_SWITCH_OFF"},
	{GAMESOUNDS_SWITCH_ON, "SOUND_ID_SWITCH_ON"},
	{GAMESOUNDS_SYS_BUSY, "SOUND_ID_SYS_BUSY"},
	{GAMESOUNDS_TUTORIAL, "SOUND_ID_TUTORIAL"},
	{GAMESOUNDS_VICTORY_FANFARE, "SOUND_ID_VICTORY_FANFARE"},
	{GAMESOUNDS_VOLUME_DOWN, "SOUND_ID_VOLUME_DOWN"},
	{GAMESOUNDS_VOLUME_UP, "SOUND_ID_VOLUME_UP"},
	{GAMESOUNDS_POTTY, "SOUND_POTTY"},
	{GAMESOUNDS_BACK_TO_WORK, "SOUND_BACK_TO_WORK"},
	{GAMESOUNDS_HACKNEYED, "SOUND_HACKNEYED"},
	{GAMESOUNDS_ARCHER_A, "SOUND_ARCHER_A"},
	{GAMESOUNDS_ARCHER_B, "SOUND_ARCHER_B"},
	{GAMESOUNDS_ARCHER_C, "SOUND_ARCHER_C"}, 
	{GAMESOUNDS_ARCHER_D, "SOUND_ARCHER_D"}, 

	{GAMESOUNDS_MAX,			""},
};

sint32 gamesounds_GetGameSoundID(sint32 gamesound)
{
	sint32 index;

	if (gamesound < 0 || gamesound >= GAMESOUNDS_MAX) return 0;

	if ((index = g_theSoundDB->FindTypeIndex(g_gameSounds[gamesound].name)) != -1) {
		return index;
	} else {
		return 0;
	}
}

void gamesounds_WindowOpened(void)
{
	if (g_soundManager) {
		g_soundManager->AddSound(SOUNDTYPE_SFX, 0, 
				gamesounds_GetGameSoundID(GAMESOUNDS_MAXWINDOW), 0, 0);
	}
}

void gamesounds_WindowClosed(void)
{
	if (g_soundManager) {
		g_soundManager->AddSound(SOUNDTYPE_SFX, 0, 
				gamesounds_GetGameSoundID(GAMESOUNDS_MINWINDOW), 0, 0);
	}
}
