dnl This file is published under LGPL

AC_DEFUN([AM_PATH_DIRECTX],[
	AC_PREREQ(2.13)
	AC_REQUIRE([AC_CANONICAL_HOST])

case $host in
*-cygwin*)
	DIRECTX_SDKDIR="C:\\DX90BSDK"
	DIRECTX_INCLUDES="-I \"${DIRECTX_SDKDIR}\\include\"" 
	DIRECTX_LDADD=""

	AC_SUBST(DIRECTX_SDKDIR)
	AC_SUBST(DIRECTX_INCLUDES)
	AC_SUBST(DIRECTX_LDADD)
	;;
esac
])
