









#pragma once
#ifndef _NET_ACTION_H_
#define _NET_ACTION_H_

#include "net_packet.h"
#include "MapPoint.h"

enum NET_ACTION {
	NET_ACTION_MOVE_UNIT,
	NET_ACTION_END_TURN,
	NET_ACTION_SETTLE,
	NET_ACTION_BUILD,
	NET_ACTION_TAX_RATES,
	NET_ACTION_BUILD_IMP,
	NET_ACTION_CREATE_TRADE_ROUTE,
	NET_ACTION_CANCEL_TRADE_ROUTE,
	NET_ACTION_CREATE_TRADE_OFFER,
	NET_ACTION_WITHDRAW_TRADE_OFFER,
	NET_ACTION_CREATED_POP,
	NET_ACTION_CREATED_UNIT,
	NET_ACTION_SET_READINESS,
	NET_ACTION_TERRAIN_IMPROVEMENT,
	NET_ACTION_CREATE_INSTALLATION,
	NET_ACTION_ENTRENCH,
	NET_ACTION_DETRENCH,
	NET_ACTION_SLEEP,
	NET_ACTION_WAKEUP,
	NET_ACTION_SET_MATERIALS_TAX,
	NET_ACTION_FOLLOW_PATH,
	NET_ACTION_FOLLOW_PATROL,
	NET_ACTION_DEL_TAIL_ORDER,
	NET_ACTION_POP_TO_CITY,
	NET_ACTION_POP_TO_FIELD,
	NET_ACTION_BUILD_WONDER,
	NET_ACTION_INTERCEPT_TRADE,
	NET_ACTION_WORKDAY_LEVEL,
	NET_ACTION_WAGES_LEVEL,
	NET_ACTION_RATIONS_LEVEL,
	NET_ACTION_CREATED_CIV,
	NET_ACTION_CREATE_DIP_REQUEST,

	NET_ACTION_UNLOAD_TRANSPORT,
	NET_ACTION_GROUP_ARMY,
	NET_ACTION_UNGROUP_ARMY,
	NET_ACTION_PARADROP,
	NET_ACTION_SPACE_LAUNCH,
	NET_ACTION_INVESTIGATE_CITY,
	NET_ACTION_NULLIFY_WALLS,
	NET_ACTION_STEAL_TECHNOLOGY,
	NET_ACTION_INCITE_REVOLUTION,
	NET_ACTION_ASSASSINATE_RULER,
	NET_ACTION_INVESTIGATE_READINESS,
	NET_ACTION_BOMBARD,
	NET_ACTION_SUE,
	NET_ACTION_SUE_FRANCHISE,
	NET_ACTION_EXPEL,
	NET_ACTION_CAUSE_UNHAPPINESS,
	NET_ACTION_PLANT_NUKE,
	NET_ACTION_SLAVE_RAID,
	NET_ACTION_ENSLAVE_SETTLER,
	NET_ACTION_UNDERGROUND_RAILWAY,
	NET_ACTION_INCITE_UPRISING,
	NET_ACTION_BIO_INFECT,
	NET_ACTION_NANO_INFECT,
	NET_ACTION_CONVERT_CITY,
	NET_ACTION_REFORM_CITY,
	NET_ACTION_SOOTHSAY,
	NET_ACTION_DEFUSE_MINES,
	NET_ACTION_FRANCHISE,
	NET_ACTION_INDULGENCE_SALE,
	NET_ACTION_CLOAK,
	NET_ACTION_UNCLOAK,
	NET_ACTION_RUSTLE,
	NET_ACTION_CREATE_PARK,
	NET_ACTION_CREATE_RIFT,

	NET_ACTION_REJECT_MESSAGE,
	NET_ACTION_OK_MESSAGE,
	NET_ACTION_IGNORE_MESSAGE,
	NET_ACTION_DISMISS_MESSAGE,
	NET_ACTION_ACCEPT_MESSAGE,

	NET_ACTION_SET_THIRD_PARTY,
	NET_ACTION_SET_RESPONSE,
	NET_ACTION_SET_REWARD_GOLD,
	NET_ACTION_SET_REWARD_CITY,
	NET_ACTION_SET_REWARD_ADVANCE,
	NET_ACTION_SET_TARGET_CITY,
	NET_ACTION_SET_REQUEST_GOLD,
	NET_ACTION_SET_ADVANCE,
	NET_ACTION_SET_WANTED_ADVANCE,
	NET_ACTION_SET_WANTED_CITY,

	NET_ACTION_PILLAGE,
	NET_ACTION_RESEARCH,

	NET_ACTION_KILLED_PLAYER,
	NET_ACTION_INJOIN,
	NET_ACTION_CHANGE_BUILD,

	NET_ACTION_DEFAULT_PLACE_POP,
	NET_ACTION_SET_POP_TYPE,
	NET_ACTION_USE_SPACE_LADDER,
	NET_ACTION_END_SLICE,
	NET_ACTION_DO_FRONT_ORDER,
	NET_ACTION_DO_SETTLE_ORDER,
	NET_ACTION_SET_GOVERNMENT,
	NET_ACTION_ENACT_REQUEST,
	NET_ACTION_REJECT_REQUEST,

	NET_ACTION_CREATE_UNIT_CHEAT,
	NET_ACTION_CREATE_CITY_CHEAT,
	NET_ACTION_DONE_SETTING_UP,
	NET_ACTION_ADVANCE_CHEAT,
	NET_ACTION_TAKE_ADVANCE_CHEAT,
	NET_ACTION_CHEAT_ADD_MATERIALS,
	NET_ACTION_CHEAT_SUB_MATERIALS,
	NET_ACTION_CHEAT_CREATE_TERRAIN_IMPROVEMENT,
	NET_ACTION_SELL_UNITS,
	NET_ACTION_SELL_ONE_UNIT,
	NET_ACTION_SELL_IMPROVEMENTS,
	NET_ACTION_AIRLIFT,
	NET_ACTION_BUY_FRONT,
	NET_ACTION_ACK_BEGIN_TURN,
	NET_ACTION_CREATED_CITY,
	NET_ACTION_SET_POP_POS,
	NET_ACTION_POP_IN_CITY,
	NET_ACTION_SELL_BUILDING,
	NET_ACTION_SET_OPTIMAL_OUTPUT,
	NET_ACTION_ACTUALLY_SET_GOVERNMENT,
	NET_ACTION_REMOVE_BUILD_ITEM,
	NET_ACTION_CLEAR_ORDERS,
	NET_ACTION_EXECUTE_ORDERS,
	NET_ACTION_CREATED_ARMY,
	NET_ACTION_SEND_TRADE_BID,
	NET_ACTION_ACCEPT_TRADE_BID,
	NET_ACTION_REJECT_TRADE_BID,
	NET_ACTION_CREATE_OWN_ARMY,
	NET_ACTION_SEND_SLAVE_TO,
	NET_ACTION_NAK_BEGIN_TURN,
	NET_ACTION_SET_POP_POS_WANT_ACK,
	NET_ACTION_CLEAR_ORDERS_EXCEPT_GROUP,
	NET_ACTION_BUILD_INFRASTRUCTURE,
	NET_ACTION_BUILD_CAPITALIZATION,
	NET_ACTION_BUILD_END_GAME,
	NET_ACTION_DISBAND_CITY,
	NET_ACTION_TAKE_TRADE_OFFER,
	NET_ACTION_ACCEPT_TRADE_OFFER,
	NET_ACTION_KILL_AGREEMENT,
	NET_ACTION_BREAK_ALLIANCE,
	NET_ACTION_BREAK_CEASE_FIRE,
	NET_ACTION_CLEAR_QUEUE,
	NET_ACTION_SET_HOMELAND,
	NET_ACTION_REQUEST_RESYNC,
	NET_ACTION_ACK_RESYNC,
	NET_ACTION_VERIFY_POS,
	NET_ACTION_SET_DIP_STATE,
	NET_ACTION_KILL_ALL_TRADE_ROUTES,
	NET_ACTION_ACK_ENACT,
	NET_ACTION_ACK_REMOVE_ILLEGAL,
	NET_ACTION_CLEAR_QUEUE_EXCEPT_HEAD,
	NET_ACTION_VIOLATE_AGREEMENT,
	NET_ACTION_OFFER_REJECTED_MESSAGE,
	NET_ACTION_FINISH_BUILDING,
	NET_ACTION_FREE_SLAVES,
	NET_ACTION_TRANSPORT_SELECT,
	NET_ACTION_TRANSPORT_UNSELECT,
	NET_ACTION_RESET_ROUTE,

	NET_ACTION_SET_MAYOR,
	NET_ACTION_SET_SPECIALISTS,

	NET_ACTION_START_MOVE_PHASE,
	NET_ACTION_DECLARE_WAR,

	NET_ACTION_REQUEST_TRADE_ROUTE,
	NET_ACTION_DISBAND_UNIT,

	NET_ACTION_NULL
};

#define k_MAX_NET_ACTION_ARGS 7

class NetAction : public Packetizer
{
public:
	
	NetAction(NET_ACTION action, ...);
	NetAction();

	void Packetize(uint8* buf, uint16& size);
	void Unpacketize(uint16 id, uint8* buf, uint16 size);
private:
	NET_ACTION m_action;
	uint32 m_data[k_MAX_NET_ACTION_ARGS];
	static const uint32 m_args[NET_ACTION_NULL];
};

#else
class NetAction;
#endif
