
#pragma once
#ifndef __NET_CONST_H__
#define __NET_CONST_H__

#define k_MAX_CHAT_LEN 200

enum RESYNC_REASON {
	RESYNC_INVALID_UNIT,
	RESYNC_INVALID_POP,
	RESYNC_INVALID_INSTALLATION,
	RESYNC_INVALID_ARMY_ORDER,
	RESYNC_INVALID_ARMY_OTHER,
	RESYNC_CITY_STATS,
	RESYNC_ARMY_POS,
	RESYNC_BAD_BUILD_NODE,
	RESYNC_BAD_PLAYER,
	RESYNC_BAD_TRADE_ROUTE,
	RESYNC_PROBABLE_CHEATER,
};

#endif
