


























#pragma once
#ifndef _TIFF_
#define	_TIFF_











#define	TIFF_VERSION	42

#define	TIFF_BIGENDIAN		0x4d4d
#define	TIFF_LITTLEENDIAN	0x4949

#ifndef _TIFF_DATA_TYPEDEFS_
#define _TIFF_DATA_TYPEDEFS_








#ifdef __STDC__
typedef	signed char int8;	
#else
typedef	char int8;
#endif
typedef	unsigned char uint8;
typedef	short int16;
typedef	unsigned short uint16;	
#if defined(__alpha) || (defined(_MIPS_SZLONG) && _MIPS_SZLONG == 64)
typedef	int int32;
typedef	unsigned int uint32;	
#else
typedef	long int32;
typedef	unsigned long uint32;	
#endif
#endif 

typedef	struct {
	uint16	tiff_magic;	
	uint16	tiff_version;	
	uint32	tiff_diroff;	
} TIFFHeader;














typedef	struct {
	uint16	tdir_tag;	
	uint16	tdir_type;	
	uint32  tdir_count;	
	uint32  tdir_offset;	
} TIFFDirEntry;














typedef	enum {
	TIFF_NOTYPE	= 0,	
	TIFF_BYTE	= 1,	
	TIFF_ASCII	= 2,	
	TIFF_SHORT	= 3,	
	TIFF_LONG	= 4,	
	TIFF_RATIONAL	= 5,	
	TIFF_SBYTE	= 6,	
	TIFF_UNDEFINED	= 7,	
	TIFF_SSHORT	= 8,	
	TIFF_SLONG	= 9,	
	TIFF_SRATIONAL	= 10,	
	TIFF_FLOAT	= 11,	
	TIFF_DOUBLE	= 12	
} TIFFDataType;




#define	TIFFTAG_SUBFILETYPE		254	
#define	    FILETYPE_REDUCEDIMAGE	0x1	
#define	    FILETYPE_PAGE		0x2	
#define	    FILETYPE_MASK		0x4	
#define	TIFFTAG_OSUBFILETYPE		255	
#define	    OFILETYPE_IMAGE		1	
#define	    OFILETYPE_REDUCEDIMAGE	2	
#define	    OFILETYPE_PAGE		3	
#define	TIFFTAG_IMAGEWIDTH		256	
#define	TIFFTAG_IMAGELENGTH		257	
#define	TIFFTAG_BITSPERSAMPLE		258	
#define	TIFFTAG_COMPRESSION		259	
#define	    COMPRESSION_NONE		1	
#define	    COMPRESSION_CCITTRLE	2	
#define	    COMPRESSION_CCITTFAX3	3	
#define	    COMPRESSION_CCITTFAX4	4	
#define	    COMPRESSION_LZW		5	
#define	    COMPRESSION_OJPEG		6	
#define	    COMPRESSION_JPEG		7	
#define	    COMPRESSION_NEXT		32766	
#define	    COMPRESSION_CCITTRLEW	32771	
#define	    COMPRESSION_PACKBITS	32773	
#define	    COMPRESSION_THUNDERSCAN	32809	

#define	    COMPRESSION_IT8CTPAD	32895   
#define	    COMPRESSION_IT8LW		32896   
#define	    COMPRESSION_IT8MP		32897   
#define	    COMPRESSION_IT8BL		32898   

#define     COMPRESSION_PIXARFILM	32908   
#define	    COMPRESSION_PIXARLOG	32909   
#define	    COMPRESSION_DEFLATE		32946	

#define     COMPRESSION_DCS             32947   
#define	    COMPRESSION_JBIG		34661	
#define     COMPRESSION_SGILOG		34676	
#define     COMPRESSION_SGILOG24	34677	
#define	TIFFTAG_PHOTOMETRIC		262	
#define	    PHOTOMETRIC_MINISWHITE	0	
#define	    PHOTOMETRIC_MINISBLACK	1	
#define	    PHOTOMETRIC_RGB		2	
#define	    PHOTOMETRIC_PALETTE		3	
#define	    PHOTOMETRIC_MASK		4	
#define	    PHOTOMETRIC_SEPARATED	5	
#define	    PHOTOMETRIC_YCBCR		6	
#define	    PHOTOMETRIC_CIELAB		8	
#define     PHOTOMETRIC_LOGL		32844	
#define     PHOTOMETRIC_LOGLUV		32845	
#define	TIFFTAG_THRESHHOLDING		263	
#define	    THRESHHOLD_BILEVEL		1	
#define	    THRESHHOLD_HALFTONE		2	
#define	    THRESHHOLD_ERRORDIFFUSE	3	
#define	TIFFTAG_CELLWIDTH		264	
#define	TIFFTAG_CELLLENGTH		265	
#define	TIFFTAG_FILLORDER		266	
#define	    FILLORDER_MSB2LSB		1	
#define	    FILLORDER_LSB2MSB		2	
#define	TIFFTAG_DOCUMENTNAME		269	
#define	TIFFTAG_IMAGEDESCRIPTION	270	
#define	TIFFTAG_MAKE			271	
#define	TIFFTAG_MODEL			272	
#define	TIFFTAG_STRIPOFFSETS		273	
#define	TIFFTAG_ORIENTATION		274	
#define	    ORIENTATION_TOPLEFT		1	
#define	    ORIENTATION_TOPRIGHT	2	
#define	    ORIENTATION_BOTRIGHT	3	
#define	    ORIENTATION_BOTLEFT		4	
#define	    ORIENTATION_LEFTTOP		5	
#define	    ORIENTATION_RIGHTTOP	6	
#define	    ORIENTATION_RIGHTBOT	7	
#define	    ORIENTATION_LEFTBOT		8	
#define	TIFFTAG_SAMPLESPERPIXEL		277	
#define	TIFFTAG_ROWSPERSTRIP		278	
#define	TIFFTAG_STRIPBYTECOUNTS		279	
#define	TIFFTAG_MINSAMPLEVALUE		280	
#define	TIFFTAG_MAXSAMPLEVALUE		281	
#define	TIFFTAG_XRESOLUTION		282	
#define	TIFFTAG_YRESOLUTION		283	
#define	TIFFTAG_PLANARCONFIG		284	
#define	    PLANARCONFIG_CONTIG		1	
#define	    PLANARCONFIG_SEPARATE	2	
#define	TIFFTAG_PAGENAME		285	
#define	TIFFTAG_XPOSITION		286	
#define	TIFFTAG_YPOSITION		287	
#define	TIFFTAG_FREEOFFSETS		288	
#define	TIFFTAG_FREEBYTECOUNTS		289	
#define	TIFFTAG_GRAYRESPONSEUNIT	290	
#define	    GRAYRESPONSEUNIT_10S	1	
#define	    GRAYRESPONSEUNIT_100S	2	
#define	    GRAYRESPONSEUNIT_1000S	3	
#define	    GRAYRESPONSEUNIT_10000S	4	
#define	    GRAYRESPONSEUNIT_100000S	5	
#define	TIFFTAG_GRAYRESPONSECURVE	291	
#define	TIFFTAG_GROUP3OPTIONS		292	
#define	    GROUP3OPT_2DENCODING	0x1	
#define	    GROUP3OPT_UNCOMPRESSED	0x2	
#define	    GROUP3OPT_FILLBITS		0x4	
#define	TIFFTAG_GROUP4OPTIONS		293	
#define	    GROUP4OPT_UNCOMPRESSED	0x2	
#define	TIFFTAG_RESOLUTIONUNIT		296	
#define	    RESUNIT_NONE		1	
#define	    RESUNIT_INCH		2	
#define	    RESUNIT_CENTIMETER		3	
#define	TIFFTAG_PAGENUMBER		297	
#define	TIFFTAG_COLORRESPONSEUNIT	300	
#define	    COLORRESPONSEUNIT_10S	1	
#define	    COLORRESPONSEUNIT_100S	2	
#define	    COLORRESPONSEUNIT_1000S	3	
#define	    COLORRESPONSEUNIT_10000S	4	
#define	    COLORRESPONSEUNIT_100000S	5	
#define	TIFFTAG_TRANSFERFUNCTION	301	
#define	TIFFTAG_SOFTWARE		305	
#define	TIFFTAG_DATETIME		306	
#define	TIFFTAG_ARTIST			315	
#define	TIFFTAG_HOSTCOMPUTER		316	
#define	TIFFTAG_PREDICTOR		317	
#define	TIFFTAG_WHITEPOINT		318	
#define	TIFFTAG_PRIMARYCHROMATICITIES	319	
#define	TIFFTAG_COLORMAP		320	
#define	TIFFTAG_HALFTONEHINTS		321	
#define	TIFFTAG_TILEWIDTH		322	
#define	TIFFTAG_TILELENGTH		323	
#define TIFFTAG_TILEOFFSETS		324	
#define TIFFTAG_TILEBYTECOUNTS		325	
#define	TIFFTAG_BADFAXLINES		326	
#define	TIFFTAG_CLEANFAXDATA		327	
#define	    CLEANFAXDATA_CLEAN		0	
#define	    CLEANFAXDATA_REGENERATED	1	
#define	    CLEANFAXDATA_UNCLEAN	2	
#define	TIFFTAG_CONSECUTIVEBADFAXLINES	328	
#define	TIFFTAG_SUBIFD			330	
#define	TIFFTAG_INKSET			332	
#define	    INKSET_CMYK			1	
#define	TIFFTAG_INKNAMES		333	
#define	TIFFTAG_NUMBEROFINKS		334	
#define	TIFFTAG_DOTRANGE		336	
#define	TIFFTAG_TARGETPRINTER		337	
#define	TIFFTAG_EXTRASAMPLES		338	
#define	    EXTRASAMPLE_UNSPECIFIED	0	
#define	    EXTRASAMPLE_ASSOCALPHA	1	
#define	    EXTRASAMPLE_UNASSALPHA	2	
#define	TIFFTAG_SAMPLEFORMAT		339	
#define	    SAMPLEFORMAT_UINT		1	
#define	    SAMPLEFORMAT_INT		2	
#define	    SAMPLEFORMAT_IEEEFP		3	
#define	    SAMPLEFORMAT_VOID		4	
#define	TIFFTAG_SMINSAMPLEVALUE		340	
#define	TIFFTAG_SMAXSAMPLEVALUE		341	
#define	TIFFTAG_JPEGTABLES		347	




#define	TIFFTAG_JPEGPROC		512	
#define	    JPEGPROC_BASELINE		1	
#define	    JPEGPROC_LOSSLESS		14	
#define	TIFFTAG_JPEGIFOFFSET		513	
#define	TIFFTAG_JPEGIFBYTECOUNT		514	
#define	TIFFTAG_JPEGRESTARTINTERVAL	515	
#define	TIFFTAG_JPEGLOSSLESSPREDICTORS	517	
#define	TIFFTAG_JPEGPOINTTRANSFORM	518	
#define	TIFFTAG_JPEGQTABLES		519	
#define	TIFFTAG_JPEGDCTABLES		520	
#define	TIFFTAG_JPEGACTABLES		521	
#define	TIFFTAG_YCBCRCOEFFICIENTS	529	
#define	TIFFTAG_YCBCRSUBSAMPLING	530	
#define	TIFFTAG_YCBCRPOSITIONING	531	
#define	    YCBCRPOSITION_CENTERED	1	
#define	    YCBCRPOSITION_COSITED	2	
#define	TIFFTAG_REFERENCEBLACKWHITE	532	

#define TIFFTAG_REFPTS			32953	
#define TIFFTAG_REGIONTACKPOINT		32954	
#define TIFFTAG_REGIONWARPCORNERS	32955	
#define TIFFTAG_REGIONAFFINE		32956	

#define	TIFFTAG_MATTEING		32995	
#define	TIFFTAG_DATATYPE		32996	
#define	TIFFTAG_IMAGEDEPTH		32997	
#define	TIFFTAG_TILEDEPTH		32998	








#define TIFFTAG_PIXAR_IMAGEFULLWIDTH    33300   
#define TIFFTAG_PIXAR_IMAGEFULLLENGTH   33301   

#define TIFFTAG_WRITERSERIALNUMBER      33405   

#define	TIFFTAG_COPYRIGHT		33432	

#define TIFFTAG_IT8SITE			34016	
#define TIFFTAG_IT8COLORSEQUENCE	34017	
#define TIFFTAG_IT8HEADER		34018	
#define TIFFTAG_IT8RASTERPADDING	34019	
#define TIFFTAG_IT8BITSPERRUNLENGTH	34020	
#define TIFFTAG_IT8BITSPEREXTENDEDRUNLENGTH 34021
#define TIFFTAG_IT8COLORTABLE		34022	
#define TIFFTAG_IT8IMAGECOLORINDICATOR	34023	
#define TIFFTAG_IT8BKGCOLORINDICATOR	34024	
#define TIFFTAG_IT8IMAGECOLORVALUE	34025	
#define TIFFTAG_IT8BKGCOLORVALUE	34026	
#define TIFFTAG_IT8PIXELINTENSITYRANGE	34027	
#define TIFFTAG_IT8TRANSPARENCYINDICATOR 34028	
#define TIFFTAG_IT8COLORCHARACTERIZATION 34029	

#define TIFFTAG_FRAMECOUNT              34232   

#define TIFFTAG_ICCPROFILE		34675	

#define	TIFFTAG_JBIGOPTIONS		34750	

#define	TIFFTAG_FAXRECVPARAMS		34908	
#define	TIFFTAG_FAXSUBADDRESS		34909	
#define	TIFFTAG_FAXRECVTIME		34910	

#define TIFFTAG_STONITS			37439	

#define	TIFFTAG_FEDEX_EDR		34929	

#define TIFFTAG_DCSHUESHIFTVALUES       65535   












#define	TIFFTAG_FAXMODE			65536	
#define	    FAXMODE_CLASSIC	0x0000		
#define	    FAXMODE_NORTC	0x0001		
#define	    FAXMODE_NOEOL	0x0002		
#define	    FAXMODE_BYTEALIGN	0x0004		
#define	    FAXMODE_WORDALIGN	0x0008		
#define	    FAXMODE_CLASSF	FAXMODE_NORTC	
#define	TIFFTAG_JPEGQUALITY		65537	

#define	TIFFTAG_JPEGCOLORMODE		65538	
#define	    JPEGCOLORMODE_RAW	0x0000		
#define	    JPEGCOLORMODE_RGB	0x0001		
#define	TIFFTAG_JPEGTABLESMODE		65539	
#define	    JPEGTABLESMODE_QUANT 0x0001		
#define	    JPEGTABLESMODE_HUFF	0x0002		

#define	TIFFTAG_FAXFILLFUNC		65540	
#define	TIFFTAG_PIXARLOGDATAFMT		65549	
#define	    PIXARLOGDATAFMT_8BIT	0	
#define	    PIXARLOGDATAFMT_8BITABGR	1	
#define	    PIXARLOGDATAFMT_11BITLOG	2	
#define	    PIXARLOGDATAFMT_12BITPICIO	3	
#define	    PIXARLOGDATAFMT_16BIT	4	
#define	    PIXARLOGDATAFMT_FLOAT	5	

#define TIFFTAG_DCSIMAGERTYPE           65550   
#define     DCSIMAGERMODEL_M3           0       
#define     DCSIMAGERMODEL_M5           1       
#define     DCSIMAGERMODEL_M6           2       
#define     DCSIMAGERFILTER_IR          0       
#define     DCSIMAGERFILTER_MONO        1       
#define     DCSIMAGERFILTER_CFA         2       
#define     DCSIMAGERFILTER_OTHER       3       
#define TIFFTAG_DCSINTERPMODE           65551   
#define     DCSINTERPMODE_NORMAL        0x0     
#define     DCSINTERPMODE_PREVIEW       0x1     
#define TIFFTAG_DCSBALANCEARRAY         65552   
#define TIFFTAG_DCSCORRECTMATRIX        65553   
#define TIFFTAG_DCSGAMMA                65554   
#define TIFFTAG_DCSTOESHOULDERPTS       65555   
#define TIFFTAG_DCSCALIBRATIONFD        65556   

#define	TIFFTAG_ZIPQUALITY		65557	
#define	TIFFTAG_PIXARLOGQUALITY		65558	

#define TIFFTAG_DCSCLIPRECTANGLE	65559	
#define TIFFTAG_SGILOGDATAFMT		65560	
#define     SGILOGDATAFMT_FLOAT		0	
#define     SGILOGDATAFMT_16BIT		1	
#define     SGILOGDATAFMT_RAW		2	
#define     SGILOGDATAFMT_8BIT		3	
#endif 
