#ifndef __AUITYPES_H__
#define __AUITYPES_H__

#include "ctp2_inttypes.h"

enum AUI_ERRCODE
{
	AUI_ERRCODE_HACK = -1,




	AUI_ERRCODE_FIRST = 0,
	AUI_ERRCODE_OK = 0,
	AUI_ERRCODE_LOADFAILED,
	AUI_ERRCODE_UNLOADFAILED,
	AUI_ERRCODE_MEMALLOCFAILED,
	AUI_ERRCODE_INVALIDPARAM,
	AUI_ERRCODE_INVALIDDIMENSION,
	AUI_ERRCODE_INVALIDFLAG,
	AUI_ERRCODE_BADPIXELFORMAT,
	AUI_ERRCODE_SUSPENDFAILED,
	AUI_ERRCODE_RESUMEFAILED,
	AUI_ERRCODE_BLTFAILED,
	AUI_ERRCODE_NOPICKUPS,
	AUI_ERRCODE_NOINPUT,
	AUI_ERRCODE_NOTACQUIRED,
	AUI_ERRCODE_INPUTLOST,
	AUI_ERRCODE_ACQUIREFAILED,
	AUI_ERRCODE_UNACQUIREFAILED,
	AUI_ERRCODE_SURFACEBUSY,
	AUI_ERRCODE_SURFACELOCKFAILED,
	AUI_ERRCODE_SURFACEUNLOCKFAILED,
	AUI_ERRCODE_SURFACEMAXLOCKED,
	AUI_ERRCODE_SURFACENOTLOCKED,
	AUI_ERRCODE_LOCKED,
	AUI_ERRCODE_UNLOCKED,
	AUI_ERRCODE_SURFACEFAILURE,
	AUI_ERRCODE_WINDOWFAILURE,
	AUI_ERRCODE_CONTROLFAILURE,
	AUI_ERRCODE_LISTFAILURE,
	AUI_ERRCODE_LISTBOXFAILURE,
	AUI_ERRCODE_BUTTONFAILURE,
	AUI_ERRCODE_SWITCHFAILURE,
	AUI_ERRCODE_SWITCHGROUPFAILURE,
	AUI_ERRCODE_RANGERFAILURE,
	AUI_ERRCODE_CREATEEVENTFAILED,
	AUI_ERRCODE_SETEVENTFAILED,
	AUI_ERRCODE_NOUI,
	AUI_ERRCODE_NOBLITTER,
	AUI_ERRCODE_NOMOUSE,
	AUI_ERRCODE_NOSURFACE,
	AUI_ERRCODE_NOWINDOW,
	AUI_ERRCODE_NOIMAGE,
	AUI_ERRCODE_NOCONTROL,
	AUI_ERRCODE_NODIRTYLIST,
	AUI_ERRCODE_NOWINDOWLIST,
	AUI_ERRCODE_NODRAWHANDLER,
	AUI_ERRCODE_NOEVENTHANDLER,
	AUI_ERRCODE_NOTHREAD,
	AUI_ERRCODE_NODSAUDIO,
	AUI_ERRCODE_UNKNOWNIMAGETYPE,
	AUI_ERRCODE_SETDISPLAYFAILED,
	AUI_ERRCODE_UNHANDLED,
	AUI_ERRCODE_HANDLED,
	AUI_ERRCODE_HANDLEDEXCLUSIVE,
	AUI_ERRCODE_LDLFILEREADFAILED,
	AUI_ERRCODE_LDLFILEWRITEFAILED,
	AUI_ERRCODE_LDLFINDDATABLOCKFAILED,
	AUI_ERRCODE_LDLGETVALUEFAILED,
	AUI_ERRCODE_RESIZEFAILED,
	AUI_ERRCODE_MOVEFAILED,
	AUI_ERRCODE_DONTDRAWCHILDREN,
//#ifdef __AUI_USE_DIRECTX__
	AUI_ERRCODE_CREATEFAILED,
	AUI_ERRCODE_SETCOOPLEVELFAILED,
	AUI_ERRCODE_CREATESURFACEFAILED,
	AUI_ERRCODE_GETDEVICEDATAFAILED,
	AUI_ERRCODE_NODIRECTINPUTDEVICE,
	AUI_ERRCODE_SETPROPERTYFAILED,
	AUI_ERRCODE_SETFORMATFAILED,
//#endif
	AUI_ERRCODE_MOVIEFAILED,
	AUI_ERRCODE_MAX
};

#define Mod(a,m)			((a)-(m)*(sint32)floor((double)(a)/(double)(m)))

#define AUI_SUCCESS(err)	((err)==AUI_ERRCODE_OK)
#define AUI_NEWOK(obj,err)	((obj)&&AUI_SUCCESS(err))

#if defined(WIN32)
// _TCHAR has been predefined
#else
typedef char                _TCHAR; // TODO: or wchar_t, for Unicode
#endif

typedef _TCHAR              tchar;
typedef tchar               MBCHAR;
typedef MBCHAR*             LPMBCHAR;

#endif
