#pragma once
#ifndef __SLIC_BUILTIN_ENUM_H__
#define __SLIC_BUILTIN_ENUM_H__

enum SLIC_BUILTIN {
	SLIC_BUILTIN_PLAYER,
	SLIC_BUILTIN_CITY,
	SLIC_BUILTIN_UNIT,
	SLIC_BUILTIN_GLOBAL,
	SLIC_BUILTIN_ARMY,
	SLIC_BUILTIN_LOCATION,

	SLIC_BUILTIN_ADVANCE,
	SLIC_BUILTIN_GOVERNMENT,
	SLIC_BUILTIN_GOLD,
	SLIC_BUILTIN_POP,
	SLIC_BUILTIN_GOOD,
	SLIC_BUILTIN_ACTION,
	SLIC_BUILTIN_IMPROVEMENT,
	SLIC_BUILTIN_VALUE,
	SLIC_BUILTIN_BUILDING,
	SLIC_BUILTIN_WONDER,
	SLIC_BUILTIN_UNITRECORD,

	SLIC_BUILTIN_MAX
};

#endif
