//
// C++ Interface: ctp2_enums
//
// Description: 
//
//
// Author:  <ctp2source@apolyton.net>, (C) 2005
//
// Copyright: See COPYING file that comes with this distribution
//
//
#ifdef HAVE_PRAGMA_ONCE
#pragma once
#endif

#ifndef __ctp__ctp2_enums_h__
#define __ctp__ctp2_enums_h__ 1

enum CONVERTED_BY {
	CONVERTED_BY_CLERIC,
	CONVERTED_BY_TELEVANGELIST,
	CONVERTED_BY_NOTHING
};

#include "GameOver.h"

enum HAPPY_REASON {
	HAPPY_REASON_SMOKING_CRACK = -1,

	
	HAPPY_REASON_CITY_SIZE,
	HAPPY_REASON_DISTANCE_FROM_CAPITOL,
	HAPPY_REASON_ENEMY_ACTION,
	HAPPY_REASON_POLLUTION,
	HAPPY_REASON_STARVATION,
	HAPPY_REASON_PEACE_MOVEMENT,
	HAPPY_REASON_WORKDAY,
	HAPPY_REASON_WAGES,
	HAPPY_REASON_RATIONS,
	HAPPY_REASON_MARTIAL_LAW,
	HAPPY_REASON_ENTERTAINERS,
	HAPPY_REASON_BUILDINGS,
	HAPPY_REASON_WONDERS,
	HAPPY_REASON_CRIME,
	HAPPY_REASON_CONQUEST_DISTRESS,
	HAPPY_REASON_NUM_CITIES,
	HAPPY_REASON_FEATS,
	
	
	

	
	HAPPY_REASON_HAPPINESS_ATTACK,
	HAPPY_REASON_SLAVES_TAKEN,
	HAPPY_REASON_INDULGENCES,
	HAPPY_REASON_BIO_INFECTION,
	HAPPY_REASON_REFORMATION,
	HAPPY_REASON_POP_TYPE_REMOVED,
	HAPPY_REASON_POP_TYPE_ADDED,
	HAPPY_REASON_SOOTHSAY,
	HAPPY_REASON_EMANCIPATION,
	HAPPY_REASON_ATTACKED_CONVERTER,

	HAPPY_REASON_POST_REVOULTION_BLISS,  
	HAPPY_REASON_WONDER_TURNS_REMAINING,
	HAPPY_REASON_ASSASSINATION,
	HAPPY_REASON_MAX
};


enum UNIT_ORDER_TYPE {
	UNIT_ORDER_NONE,
	UNIT_ORDER_MOVE,
	UNIT_ORDER_PATROL,
	UNIT_ORDER_CIRCULAR_PATROL,
	UNIT_ORDER_ENTRENCH,
	UNIT_ORDER_SLEEP,
	UNIT_ORDER_DETRENCH,
	UNIT_ORDER_UNLOAD,
	UNIT_ORDER_MOVE_TO,
	UNIT_ORDER_TELEPORT_TO,

	
	UNIT_ORDER_EXPEL_TO,
	UNIT_ORDER_GROUP,
	UNIT_ORDER_UNGROUP,
	UNIT_ORDER_INVESTIGATE_CITY,
	UNIT_ORDER_NULLIFY_WALLS,
	UNIT_ORDER_STEAL_TECHNOLOGY,
	UNIT_ORDER_INCITE_REVOLUTION,
	UNIT_ORDER_ASSASSINATE,
	UNIT_ORDER_INVESTIGATE_READINESS,
	UNIT_ORDER_BOMBARD,

	
	UNIT_ORDER_SUE,
	UNIT_ORDER_FRANCHISE,
	UNIT_ORDER_SUE_FRANCHISE,
	UNIT_ORDER_EXPEL,
	UNIT_ORDER_ESTABLISH_EMBASSY,
	UNIT_ORDER_THROW_PARTY,
	UNIT_ORDER_CAUSE_UNHAPPINESS,
	UNIT_ORDER_PLANT_NUKE,
	UNIT_ORDER_SLAVE_RAID,
	UNIT_ORDER_ENSLAVE_SETTLER,

	
	UNIT_ORDER_UNDERGROUND_RAILWAY,
	UNIT_ORDER_INCITE_UPRISING,
	UNIT_ORDER_BIO_INFECT,
	UNIT_ORDER_NANO_INFECT,
	UNIT_ORDER_CONVERT,
	UNIT_ORDER_REFORM,
	UNIT_ORDER_INDULGENCE,
	UNIT_ORDER_SOOTHSAY,
	UNIT_ORDER_CREATE_PARK,
	UNIT_ORDER_PILLAGE,

	
	UNIT_ORDER_INJOIN,
	UNIT_ORDER_INTERCEPT_TRADE,
	UNIT_ORDER_PARADROP_MOVE,
	UNIT_ORDER_SET_UNLOAD_MOVEMENT_POINTS,
	UNIT_ORDER_GROUP_UNIT,
	UNIT_ORDER_DISBAND,
	UNIT_ORDER_FINISH_ATTACK,
	UNIT_ORDER_UNLOAD_ONE_UNIT,
	UNIT_ORDER_BOARD_TRANSPORT,
	UNIT_ORDER_WAKE_UP,

	
	UNIT_ORDER_PILLAGE_UNCONDITIONALLY,
	UNIT_ORDER_MOVE_THEN_UNLOAD,
	UNIT_ORDER_ADVERTISE,
    UNIT_ORDER_INFORM_AI_CAPTURE_CITY, 
	UNIT_ORDER_UNLOAD_SELECTED_STACK,
	UNIT_ORDER_ADD_EVENT,
	UNIT_ORDER_SETTLE, 
	UNIT_ORDER_LAUNCH,
	UNIT_ORDER_TARGET,
	UNIT_ORDER_CLEAR_TARGET,

	
	UNIT_ORDER_PLAGUE,
	UNIT_ORDER_VICTORY_MOVE,

	UNIT_ORDER_MAX
};

enum ORDER_RESULT {
	ORDER_RESULT_ILLEGAL,
	ORDER_RESULT_FAILED,
	ORDER_RESULT_SUCCEEDED,
	ORDER_RESULT_INCOMPLETE,
	ORDER_RESULT_SUCCEEDED_INCOMPLETE,
};

// Taken from gs/gameobj/citydata.h

enum UPRISING_CAUSE {
	UPRISING_CAUSE_NONE,
	UPRISING_CAUSE_SLAVE_STARVED,
	UPRISING_CAUSE_UNGUARDED_SLAVES,
	UPRISING_CAUSE_INCITED,
	UPRISING_CAUSE_INTERNAL, 
};

enum POP_TYPE {
	POP_WORKER,
	POP_SCIENTIST,
	POP_ENTERTAINER,
	POP_FARMER,
	POP_LABORER,
	POP_MERCHANT,
	POP_SLAVE,
	POP_MAX
};

// Taken from gs/gameobj/UnitData.h

enum UNIT_COMMAND {
	UNIT_COMMAND_NEAREST_CITY,
	UNIT_COMMAND_NEAREST_FORT,
	UNIT_COMMAND_NEAREST_AIRFIELD,
	UNIT_COMMAND_ENTRENCH,
	UNIT_COMMAND_SLEEP
};

// Taken from gfx/spritesys/UnitActor.h

enum SPECATTACK {
	SPECATTACK_NONE = -1,

	SPECATTACK_NUKE,
	SPECATTACK_HEARGOSSIP,
	SPECATTACK_THROWPARTY,
	SPECATTACK_ESTABLISHEMBASSY,
	SPECATTACK_INCITEREVOLUTION,
	SPECATTACK_BOMBCABINET,
	SPECATTACK_CREATEFRANCHISE,
	SPECATTACK_CAUSEUNHAPPINESS,
	SPECATTACK_CONDUCTHIT,
	SPECATTACK_BIOTERROR,
	SPECATTACK_NANOTERROR,
	SPECATTACK_SLAVERAID,
	SPECATTACK_ENSLAVESETTLER,
	SPECATTACK_SLAVEUPRISING,
	SPECATTACK_FREESLAVES,
	SPECATTACK_SELLINDULGENCE,
	SPECATTACK_CONVERTCITY,
	SPECATTACK_PLANTNUKE,
	SPECATTACK_SOOTHSAY,
	SPECATTACK_CREATEPARK,
	SPECATTACK_INJOIN,
	SPECATTACK_SPY,
	SPECATTACK_STEALTECH,
	SPECATTACK_REVOLUTION,
	SPECATTACK_REFORMCITY,

	SPECATTACK_MAX
};

// Taken from gs/gameobj/TradeRouteData.h

enum ROUTE_TYPE {
	ROUTE_TYPE_RESOURCE,
	ROUTE_TYPE_FOOD,
	ROUTE_TYPE_GOLD,
	ROUTE_TYPE_SLAVE, 
};

// Taken from robotcom/Agent/CityAgent.h

enum POPTYPE {
	POPTYPE_FIRST,
	POPTYPE_WORKER=POPTYPE_FIRST,
	POPTYPE_MUSICIAN,
	POPTYPE_SCIENTIST,
	POPTYPE_GRUNT,
	POPTYPE_SLAVE,
	POPTYPE_BANKER,
	POPTYPE_LAST=POPTYPE_BANKER,
	POPTYPE_MAX,
};

// Taken from gs/gamobj/Regard.h

enum REGARD_TYPE {
	REGARD_TYPE_INSANE_HATRED,
	REGARD_TYPE_HOTWAR,
	REGARD_TYPE_COLDWAR, 
	REGARD_TYPE_NEUTRAL,
	REGARD_TYPE_FRIENDLY,
	REGARD_TYPE_LOVE
};

// Taken from ui/interface/greatlibrary.h

enum DATABASE {
	DATABASE_DEFAULT,
	DATABASE_UNITS,
	DATABASE_BUILDINGS,
	DATABASE_WONDERS,
	DATABASE_ADVANCES,
	DATABASE_TERRAIN,
	DATABASE_CONCEPTS,
	DATABASE_GOVERNMENTS,
	DATABASE_TILE_IMPROVEMENTS,
	DATABASE_RESOURCE,
	DATABASE_ORDERS,
	DATABASE_SEARCH,

	DATABASE_MAX
};

// Taken from gs/gameobj/Readiness.h

enum READINESS_LEVEL {
	READINESS_LEVEL_PEACE,
	READINESS_LEVEL_ALERT,
	READINESS_LEVEL_WAR
};

// Taken from robotcom/Top/AiMap.h

enum INSTALLATION_TYPES { 
	INSTALLATION_LISTENING_POSTS=0, 
	INSTALLATION_RADAR_STATIONS, 	
	INSTALLATION_AIR_BASES,
	INSTALLATION_FORTIFICATIONS, 
	INSTALLATION_SONAR_BUOYS,
};

// Taken from gs/gameobj/Strengths.h

enum STRENGTH_CAT {
	STRENGTH_CAT_NONE = -1,
	STRENGTH_CAT_KNOWLEDGE,
	STRENGTH_CAT_MILITARY,
	STRENGTH_CAT_POLLUTION,
	STRENGTH_CAT_TRADE,
	STRENGTH_CAT_GOLD,
	STRENGTH_CAT_POPULATION,
	STRENGTH_CAT_CITIES,
	STRENGTH_CAT_GEOGRAPHICAL,
	STRENGTH_CAT_SPACE,
	STRENGTH_CAT_UNDERSEA,
	STRENGTH_CAT_UNITS,
	STRENGTH_CAT_BUILDINGS,
	STRENGTH_CAT_WONDERS,
	STRENGTH_CAT_PRODUCTION,
	STRENGTH_CAT_MAX
};

// Taken from ui/aui_common/aui_tabgroup.h

enum AUI_TABGROUP_ALIGNMENT
{
	AUI_TABGROUP_ALIGNMENT_FIRST = 0,
	AUI_TABGROUP_ALIGNMENT_LEFT = 0,	
	AUI_TABGROUP_ALIGNMENT_TOP, 		
	AUI_TABGROUP_ALIGNMENT_RIGHT,		
	AUI_TABGROUP_ALIGNMENT_BOTTOM,		
	AUI_TABGROUP_ALIGNMENT_LAST
};

// Taken from ui/aui_ctp2/keymap.h

enum KEY_FUNCTION { 
  KEY_FUNCTION_NOOP,		
									
  KEY_FUNCTION_MOVE_NORTH,
  KEY_FUNCTION_MOVE_NORTHWEST,
  KEY_FUNCTION_MOVE_NORTHEAST,
  KEY_FUNCTION_MOVE_WEST,
  KEY_FUNCTION_MOVE_EAST,
  KEY_FUNCTION_MOVE_SOUTHWEST,
  KEY_FUNCTION_MOVE_SOUTH,
  KEY_FUNCTION_MOVE_SOUTHEAST,	
  KEY_FUNCTION_UNIT_CITY_TOGGLE,
  KEY_FUNCTION_NEXT_ITEM,
  KEY_FUNCTION_KEYBOARD_SELECT_UNIT,
  KEY_FUNCTION_NEXT_ROUND,
  KEY_FUNCTION_ENDTURN,					

  KEY_FUNCTION_OPEN_WORK_VIEW,
  KEY_FUNCTION_SLEEP,
  KEY_FUNCTION_ENTRENCH,
  KEY_FUNCTION_SETTLE, 
  KEY_FUNCTION_PILLAGE,
  KEY_FUNCTION_BOMBARD,
  KEY_FUNCTION_REFORM,
  KEY_FUNCTION_EXPEL,
  KEY_FUNCTION_UNLOAD_TRANS, 
  KEY_FUNCTION_INVESTIGATE_CITY,
  KEY_FUNCTION_PLANT_NUKE,
  KEY_FUNCTION_BIOINFECT,
  KEY_FUNCTION_NANOTERROR,
  KEY_FUNCTION_CREATE_PARK,
  KEY_FUNCTION_SPACE_LAUNCH,
  KEY_FUNCTION_DESCEND,
  KEY_FUNCTION_PARADROP,
  KEY_FUNCTION_GROUP_ARMY, 
  KEY_FUNCTION_UNGROUP_ARMY, 
  KEY_FUNCTION_MOVE_ORDER,
  KEY_FUNCTION_END_UNIT_TURN,
  KEY_FUNCTION_EXECUTE_ORDERS,
  KEY_FUNCTION_PROCESS_UNIT_ORDERS,

  KEY_FUNCTION_OPEN_CIV_STATUS,
  KEY_FUNCTION_OPEN_CITY_STATUS,
  KEY_FUNCTION_CITY_MANAGEMENT,
  KEY_FUNCTION_BUILD_QUEUE,
  KEY_FUNCTION_CLEAR_QUEUE,
  KEY_FUNCTION_OPEN_SCIENCE_STATUS,
  KEY_FUNCTION_OPEN_UNIT_STATUS,
  KEY_FUNCTION_OPEN_TRADE_STATUS,
  KEY_FUNCTION_TRADE_SUMMARY,    
  KEY_FUNCTION_OPEN_DIPLOMACY,
  KEY_FUNCTION_NEW_PROPOSAL,
  KEY_FUNCTION_OPEN_MESSAGE,
  KEY_FUNCTION_GAIA,
  KEY_FUNCTION_OPEN_GREAT_LIBRARY,
  KEY_FUNCTION_OPEN_INFO_SCREEN,
  KEY_FUNCTION_TIMELINE,
  KEY_FUNCTION_RANK,
  KEY_FUNCTION_CIV_TAB,
  KEY_FUNCTION_CITY_TAB,
  KEY_FUNCTION_UNIT_TAB,
  KEY_FUNCTION_MSG_TAB,
  KEY_FUNCTION_TILE_TAB,
  KEY_FUNCTION_CHAT_KEY,
  KEY_FUNCTION_NETWORK_PLAYERS_SCREEN,
  KEY_FUNCTION_OPEN_SCENARIO_EDITOR,
  KEY_FUNCTION_EXECUTE_EYEPOINT,
  KEY_FUNCTION_YES,
  KEY_FUNCTION_NO,

  KEY_FUNCTION_REMAP_KEYBOARD,			
  KEY_FUNCTION_OPEN_OPTIONS_SCREEN,
  KEY_FUNCTION_SOUND_OPTIONS,
  KEY_FUNCTION_GRAPHICS_OPTIONS,
  KEY_FUNCTION_GAMEPLAY_OPTIONS,
  KEY_FUNCTION_ADVANCED_OPTIONS,
  KEY_FUNCTION_RESTART,
  KEY_FUNCTION_NEW_GAME,
  KEY_FUNCTION_SAVE_GAME,
  KEY_FUNCTION_LOAD_GAME,
  KEY_FUNCTION_SAVE_WORLD,
  KEY_FUNCTION_LOAD_WORLD,
  KEY_FUNCTION_QUIT,
// MUSIC added by ahenobarb
  KEY_FUNCTION_MUSIC_OPTIONS,

  KEY_FUNCTION_TOGGLE_CITY_NAMES,
  KEY_FUNCTION_TOGGLE_TRADE_ROUTES,
  KEY_FUNCTION_CENTER_MAP,				
  KEY_FUNCTION_CLOSE,
  KEY_FUNCTION_TOGGLE_RADAR,
  KEY_FUNCTION_TOGGLE_CONTROL_PANEL,
  KEY_FUNCTION_TOGGLE_ALL,
  KEY_FUNCTION_ZOOM_IN1,
  KEY_FUNCTION_ZOOM_OUT1,
#ifdef _PLAYTEST
  KEY_FUNCTION_RAND_TEST,
  KEY_FUNCTION_GAMESTATE_DEBUG,
  KEY_FUNCTION_ENTER_COMMAND,
  KEY_FUNCTION_ENTER_COMMAND_ALTERNATE,
#endif
  KEY_FUNCTION_TOGGLE_SPACE,
		
  KEY_FUNCTION_ZOOM_OUT2,
  KEY_FUNCTION_ZOOM_IN2,
  KEY_FUNCTION_HELP_MODE_TOGGLE,
  KEY_FUNCTION_MOVE_UP_OR_DOWN,
  KEY_FUNCTION_OPEN_CITY_VIEW,
  KEY_FUNCTION_CONTROL_BUILD,
  KEY_FUNCTION_CONTROL_NEXT,
  KEY_FUNCTION_CONTROL_PREV,
  
  KEY_FUNCTION_LAST_NOOP 
};

#endif
