
#pragma once
#ifndef __MAPTOKEN_H__
#define __MAPTOKEN_H__

enum TOKEN_MAP {
	TOKEN_MAP_SIZE = TOKEN_MAX + 1,

	
	TOKEN_MAP_NUM_CONTINENTS,
	TOKEN_MAP_MIN_WIDTH,
	TOKEN_MAP_MIN_HEIGHT,
	TOKEN_MAP_MAX_WIDTH,
	TOKEN_MAP_MAX_HEIGHT,
	TOKEN_MAP_BUMP_SIZE,
	TOKEN_MAP_MIN_SUBCONTINENTS,
	TOKEN_MAP_MAX_SUBCONTINENTS,
	TOKEN_MAP_SUBCONTINENT_SIZE,
	TOKEN_MAP_SUBCONTINENT_HEIGHT,
	TOKEN_MAP_BORDER_SIZE,
	TOKEN_MAP_FAULT_LINES,
	TOKEN_MAP_FAULT_LENGTH,
	TOKEN_MAP_NS_BORDER_SIZE,
	

	TOKEN_MAP_MAX_VAL,
};

#endif
