#pragma once
#ifndef __POLLUTIONTOKEN_H__
#define __POLLUTIONTOKEN_H__

#include "Token.h"
enum TOKEN_POLLUTION
	{
	TOKEN_POLLUTION_TRIGGER_LIST_SMALL_MAP = TOKEN_MAX + 1,
	TOKEN_POLLUTION_TRIGGER_LIST_MEDIUM_MAP,
	TOKEN_POLLUTION_TRIGGER_LIST_LARGE_MAP,
	TOKEN_POLLUTION_TRIGGER_LIST_GIGANTIC_MAP,

	TOKEN_POLLUTION_TRIGGER,
	TOKEN_POLLUTION_OZONE_DISASTER,
	TOKEN_POLLUTION_FLOOD_DISASTER,
	TOKEN_POLLUTION_WARNING,

    TOKEN_POLLUTION_MAX_VAL
	} ;

#endif
