
/*
 * DO NOT EDIT THIS FILE!
 * It is generated automatically by ctpdb
 */
#include "c3.h"
#include "c3errors.h"
#include "BuildingBuildListRecord.h"
#include "DBLexer.h"
#include "DBTokens.h"
#include "CTPDatabase.h"
#include "StrDB.h"
#include "BitArray.h"

#include "BuildingRecord.h"

CTPDatabase<BuildingBuildListRecord> *g_theBuildingBuildListDB = NULL;

BuildingBuildListRecord::Init()
{
    m_Building = NULL;
    m_numBuilding = 0;
}

BuildingBuildListRecord::~BuildingBuildListRecord()
{
	int index = 0;
	// free array Building 
 	if (m_numBuilding > 0) 
		delete [m_numBuilding] m_Building; 
	m_Building = NULL; 
	m_numBuilding = 0; 

}

void BuildingBuildListRecord::operator=(const BuildingBuildListRecord & rval)
{
	int index = 0;
	m_index = rval.m_index;
	// free array Building 
 	if (m_numBuilding > 0) 
	{
		delete [m_numBuilding] m_Building; 
		m_Building = NULL; 
		m_numBuilding = 0; 
	}
	if (rval.m_numBuilding > 0) 
	{
		m_Building = new sint32 [rval.m_numBuilding]; 
		memcpy(m_Building, rval.m_Building, sizeof(sint32)*rval.m_numBuilding); 

	} 
	m_numBuilding = rval.m_numBuilding;

}

char *g_BuildingBuildList_Tokens[] =
{
    "Building",
};

BuildingBuildListRecordAccessorInfo g_BuildingBuildListRecord_Accessors[] = 
{
    { NULL, NULL, NULL, NULL, NULL}, /* Building (array) */
};

#define k_Token_BuildingBuildList_Building       ((k_Token_Custom_Base) + 0)
#define k_Token_BuildingBuildList_Max            ((k_Token_Custom_Base) + 1)


static BitArray s_ParsedTokens(1);
void BuildingBuildListRecord::CheckRequiredFields(DBLexer *lex)
{
    // Ick.
}
    
sint32 BuildingBuildListRecord::Parse(DBLexer *lex)
{
    bool done = false;
    sint32 result = 0;
    sint32 tok;
    DBPARSE_ERROR err = DBPARSE_OK;
    s_ParsedTokens.Clear();
    lex->SetTokens(g_BuildingBuildList_Tokens, k_Token_BuildingBuildList_Max);
    tok = lex->GetToken();
    if(tok != k_Token_Name) {
        DBERROR(("Record does not start with name"));
        return 0;
    }
    if(!g_theStringDB->GetStringID(lex->GetTokenText(), m_name)) {
        g_theStringDB->InsertStr(lex->GetTokenText(), lex->GetTokenText());
        if(!g_theStringDB->GetStringID(lex->GetTokenText(), m_name))
            SetTextName(lex->GetTokenText());
    }

    tok = lex->GetToken();
    if(tok != k_Token_OpenBrace) {
        DBERROR(("Missing open brace"));
        return 0;
    }

    while(!done) {
        tok = lex->GetToken();
        if(tok >= k_Token_Custom_Base && tok < k_Token_BuildingBuildList_Max) { 
            s_ParsedTokens.SetBit(tok - k_Token_Custom_Base);
        }
        switch(tok) {
            case k_Token_BuildingBuildList_Building:
                if(!g_theBuildingDB->ParseRecordInArray(lex, (sint32 **)&m_Building, &m_numBuilding, err)) 
                {
                    done = true; break;
                }
                break;
            case k_Token_CloseBrace:
                done = true;
                result = 1;
                break;
            default:
                DBERROR(("Unknown token"));
                done = true;
                break;
        }
    }
    CheckRequiredFields(lex);
    lex->RestoreTokens();
    return result;
}

void BuildingBuildListRecord::ResolveDBReferences()
{
    {
        sint32 i;
        for(i = 0; i < m_numBuilding; i++) {
            if(m_Building[i] & 0x80000000) {
                sint32 id = m_Building[i] & 0x7fffffff;
                if(!g_theBuildingDB->GetNamedItem(id, m_Building[i])) {
                    c3errors_ErrorDialog("DB", "%s not found in Building database", g_theStringDB->GetNameStr(id));
                }
            } else if(m_Building[i] == 0x7fffffff){
                m_Building[i] = -1;
            }
        }
    }
}
/*
 * Member class Parsers
 * (DO NOT EDIT!  Automatically generated file)
 */
/*
 * Data Parsers
 * (DO NOT EDIT!  Automatically generated file)
 */
void BuildingBuildListRecord::Merge(const BuildingBuildListRecord & rval){
	int index = 0, obj_index = 0;
	// resize m_Building if necessary
	if (rval.m_numBuilding > m_numBuilding)
 	{ 
		delete m_Building;
 		m_Building = NULL;
 		if (rval.m_numBuilding > 0)
 			m_Building = new sint32 [rval.m_numBuilding]; 
		m_numBuilding = rval.m_numBuilding;
 	} 

	// copy values of rval.m_Building to m_Building
	for (index = 0; index < m_numBuilding; index++) 
	{ 
 		if (index < rval.m_numBuilding)
 			m_Building[index] = rval.m_Building[index];
	} 
 } 

/*
 * Data accessors
 * (DO NOT EDIT!  Automatically generated file)
 */
sint32 BuildingBuildListRecord::GetBuildingIndex(sint32 index) const
{
    Assert(index >= 0);
    Assert(index < m_numBuilding);
    if((index < 0) || (index >= m_numBuilding)) {
        return 0;
    }
    return m_Building[index];
}

const BuildingRecord *BuildingBuildListRecord::GetBuilding(sint32 index) const
{
    Assert(index >= 0);
    Assert(index < m_numBuilding);
    if((index < 0) || (index >= m_numBuilding)) {
        return 0;
    }
    return g_theBuildingDB->Get(m_Building[index]);
}

