
/*
 * DO NOT EDIT THIS FILE!
 * It is generated automatically by ctpdb
 */
#include "c3.h"
#include "c3errors.h"
#include "UnitBuildListRecord.h"
#include "DBLexer.h"
#include "DBTokens.h"
#include "CTPDatabase.h"
#include "StrDB.h"
#include "BitArray.h"

#include "UnitRecord.h"

CTPDatabase<UnitBuildListRecord> *g_theUnitBuildListDB = NULL;

UnitBuildListRecord::Init()
{
    m_Unit = NULL;
    m_numUnit = 0;
}

UnitBuildListRecord::~UnitBuildListRecord()
{
	int index = 0;
	// free array Unit 
 	if (m_numUnit > 0) 
		delete [m_numUnit] m_Unit; 
	m_Unit = NULL; 
	m_numUnit = 0; 

}

void UnitBuildListRecord::operator=(const UnitBuildListRecord & rval)
{
	int index = 0;
	m_index = rval.m_index;
	// free array Unit 
 	if (m_numUnit > 0) 
	{
		delete [m_numUnit] m_Unit; 
		m_Unit = NULL; 
		m_numUnit = 0; 
	}
	if (rval.m_numUnit > 0) 
	{
		m_Unit = new sint32 [rval.m_numUnit]; 
		memcpy(m_Unit, rval.m_Unit, sizeof(sint32)*rval.m_numUnit); 

	} 
	m_numUnit = rval.m_numUnit;

}

char *g_UnitBuildList_Tokens[] =
{
    "Unit",
};

UnitBuildListRecordAccessorInfo g_UnitBuildListRecord_Accessors[] = 
{
    { NULL, NULL, NULL, NULL, NULL}, /* Unit (array) */
};

#define k_Token_UnitBuildList_Unit               ((k_Token_Custom_Base) + 0)
#define k_Token_UnitBuildList_Max                ((k_Token_Custom_Base) + 1)


static BitArray s_ParsedTokens(1);
void UnitBuildListRecord::CheckRequiredFields(DBLexer *lex)
{
    // Ick.
}
    
sint32 UnitBuildListRecord::Parse(DBLexer *lex)
{
    bool done = false;
    sint32 result = 0;
    sint32 tok;
    DBPARSE_ERROR err = DBPARSE_OK;
    s_ParsedTokens.Clear();
    lex->SetTokens(g_UnitBuildList_Tokens, k_Token_UnitBuildList_Max);
    tok = lex->GetToken();
    if(tok != k_Token_Name) {
        DBERROR(("Record does not start with name"));
        return 0;
    }
    if(!g_theStringDB->GetStringID(lex->GetTokenText(), m_name)) {
        g_theStringDB->InsertStr(lex->GetTokenText(), lex->GetTokenText());
        if(!g_theStringDB->GetStringID(lex->GetTokenText(), m_name))
            SetTextName(lex->GetTokenText());
    }

    tok = lex->GetToken();
    if(tok != k_Token_OpenBrace) {
        DBERROR(("Missing open brace"));
        return 0;
    }

    while(!done) {
        tok = lex->GetToken();
        if(tok >= k_Token_Custom_Base && tok < k_Token_UnitBuildList_Max) { 
            s_ParsedTokens.SetBit(tok - k_Token_Custom_Base);
        }
        switch(tok) {
            case k_Token_UnitBuildList_Unit:
                if(!g_theUnitDB->ParseRecordInArray(lex, (sint32 **)&m_Unit, &m_numUnit, err)) 
                {
                    done = true; break;
                }
                break;
            case k_Token_CloseBrace:
                done = true;
                result = 1;
                break;
            default:
                DBERROR(("Unknown token"));
                done = true;
                break;
        }
    }
    CheckRequiredFields(lex);
    lex->RestoreTokens();
    return result;
}

void UnitBuildListRecord::ResolveDBReferences()
{
    {
        sint32 i;
        for(i = 0; i < m_numUnit; i++) {
            if(m_Unit[i] & 0x80000000) {
                sint32 id = m_Unit[i] & 0x7fffffff;
                if(!g_theUnitDB->GetNamedItem(id, m_Unit[i])) {
                    c3errors_ErrorDialog("DB", "%s not found in Unit database", g_theStringDB->GetNameStr(id));
                }
            } else if(m_Unit[i] == 0x7fffffff){
                m_Unit[i] = -1;
            }
        }
    }
}
/*
 * Member class Parsers
 * (DO NOT EDIT!  Automatically generated file)
 */
/*
 * Data Parsers
 * (DO NOT EDIT!  Automatically generated file)
 */
void UnitBuildListRecord::Merge(const UnitBuildListRecord & rval){
	int index = 0, obj_index = 0;
	// resize m_Unit if necessary
	if (rval.m_numUnit > m_numUnit)
 	{ 
		delete m_Unit;
 		m_Unit = NULL;
 		if (rval.m_numUnit > 0)
 			m_Unit = new sint32 [rval.m_numUnit]; 
		m_numUnit = rval.m_numUnit;
 	} 

	// copy values of rval.m_Unit to m_Unit
	for (index = 0; index < m_numUnit; index++) 
	{ 
 		if (index < rval.m_numUnit)
 			m_Unit[index] = rval.m_Unit[index];
	} 
 } 

/*
 * Data accessors
 * (DO NOT EDIT!  Automatically generated file)
 */
sint32 UnitBuildListRecord::GetUnitIndex(sint32 index) const
{
    Assert(index >= 0);
    Assert(index < m_numUnit);
    if((index < 0) || (index >= m_numUnit)) {
        return 0;
    }
    return m_Unit[index];
}

const UnitRecord *UnitBuildListRecord::GetUnit(sint32 index) const
{
    Assert(index >= 0);
    Assert(index < m_numUnit);
    if((index < 0) || (index >= m_numUnit)) {
        return 0;
    }
    return g_theUnitDB->Get(m_Unit[index]);
}

