
/*
 * DO NOT EDIT THIS FILE!
 * It is generated automatically by ctpdb
 */
#ifndef __WonderMovie_RECORD_H__
#define __WonderMovie_RECORD_H__

/*
 * WonderMovie description
 */
#include "CTPRecord.h"
//
// Range definitions

/*
 * DO NOT EDIT THIS FILE!
 * It is generated automatically by ctpdb
 */

class WonderMovieRecord : public CTPRecord
{
public:
    typedef sint32 (WonderMovieRecord::*IntAccessor)() const;
    typedef bool (WonderMovieRecord::*BoolAccessor)() const;
    typedef double (WonderMovieRecord::*FloatAccessor)() const ;
    typedef bool (WonderMovieRecord::*BitIntAccessor)(sint32 &val) const;
    typedef bool (WonderMovieRecord::*BitFloatAccessor)(double &val) const;
private:
    char            * m_Value;
    char            * m_NameText;

public:
    WonderMovieRecord() { Init(); };
    ~WonderMovieRecord();
    Init();
    // These methods are needed for records to conform to
    // 'Orthodox Cannonical Form' and work with resizing STL vectors. 
    WonderMovieRecord(const WonderMovieRecord &rval) { Init(); *this = rval; }
    void operator=(const WonderMovieRecord &rval);

    void CheckRequiredFields(DBLexer *lex);
    sint32 Parse(DBLexer *lex);

    void ResolveDBReferences();
    void Merge(const WonderMovieRecord & rval);
    //
    // Accessors
    //
    const char      *GetValue() const { return m_Value; }
    const char      *GetNameText() const { return m_NameText; }
}; /* WonderMovieRecord */

struct WonderMovieRecordAccessorInfo {
    WonderMovieRecord::IntAccessor m_intAccessor;
    WonderMovieRecord::BoolAccessor m_boolAccessor;
    WonderMovieRecord::FloatAccessor m_floatAccessor;
    WonderMovieRecord::BitIntAccessor m_bitIntAccessor;
    WonderMovieRecord::BitFloatAccessor m_bitFloatAccessor;
};
extern WonderMovieRecordAccessorInfo g_WonderMovieRecord_Accessors[];
extern char *g_WonderMovie_Tokens[];
#define k_Num_WonderMovieRecord_Tokens 2

template <class T> class CTPDatabase;
extern CTPDatabase<WonderMovieRecord> *g_theWonderMovieDB;

#endif /* ifndef __WonderMovie_RECORD_H__ */
