# Trivial makefile for trivial Java wrapper for Activenet.
# Use nmake (watcom's make will complain that clean doesn't exist)

all:
	.\build.bat

clean:
	del *.class
	del *.dll
	del makefile~
	del *.java~
	cd Activi~1
	nmake clean
	cd ..
