#ifdef HAVE_PRAGMA_ONCE
#pragma once
#endif
#ifndef __AI_CAUSE_H__
#define __AI_CAUSE_H__ 1





enum CAUSE_REMOVE_ARMY {
    CAUSE_REMOVE_ARMY_UNKNOWN,
	CAUSE_REMOVE_ARMY_FLOOD,

    CAUSE_REMOVE_ARMY_ATTACKED,
    CAUSE_REMOVE_ARMY_CHEAT,

    CAUSE_REMOVE_ARMY_TRANSPORTED,
    CAUSE_REMOVE_ARMY_GROUPING,
    CAUSE_REMOVE_ARMY_UNGROUPING,
    CAUSE_REMOVE_ARMY_RAIL_LAUNCH,
    CAUSE_REMOVE_ARMY_PARADROP,
    CAUSE_REMOVE_ARMY_SETTLE,
    CAUSE_REMOVE_ARMY_STARVATION,
    CAUSE_REMOVE_ARMY_PARKRANGER,
    CAUSE_REMOVE_ARMY_NUKE,
    CAUSE_REMOVE_ARMY_BOMBARD,
    CAUSE_REMOVE_ARMY_SUE,
    CAUSE_REMOVE_ARMY_POLLUTION,
    CAUSE_REMOVE_ARMY_UPRISING,
    CAUSE_REMOVE_ARMY_SLAVE_UPRISING,
    CAUSE_REMOVE_ARMY_ENSLAVED,
    CAUSE_REMOVE_ARMY_DIPLOMACY,

    CAUSE_REMOVE_ARMY_NO_MAT_SUPPORT,

    CAUSE_REMOVE_ARMY_DIED_IN_ATTACK,
	CAUSE_REMOVE_ARMY_DIED_IN_ATTACK_ON_TOP,
    CAUSE_REMOVE_ARMY_DIED_IN_SPYING,
    CAUSE_REMOVE_ARMY_DIED_IN_SLAVERAID,
    CAUSE_REMOVE_ARMY_DIED_IN_UNDERGROUND_RR_RAID,
    CAUSE_REMOVE_ARMY_DIED_IN_CONVERT_RAID,
    CAUSE_REMOVE_ARMY_DIED_IN_REFORMATION,
    CAUSE_REMOVE_ARMY_COUNTERBOMBARD,
    CAUSE_REMOVE_ARMY_OUTOFFUEL,
	CAUSE_REMOVE_ARMY_REENTRY,
	CAUSE_REMOVE_ARMY_GOVERNMENT_CHANGE,
	CAUSE_REMOVE_ARMY_TOE,
    CAUSE_REMOVE_ARMY_RUSTLE,
	CAUSE_REMOVE_ARMY_LAND_MINES,
	CAUSE_REMOVE_ARMY_TRANSPORT_DIED,
	CAUSE_REMOVE_ARMY_DIDNT_NEED_IT_AFTER_ALL,
	CAUSE_REMOVE_ARMY_DISBANDED,

	CAUSE_REMOVE_ARMY_PARADROP_COMPLETE,
	CAUSE_REMOVE_ARMY_NUKES_ELIMINATED,
	CAUSE_REMOVE_ARMY_EMANCIPATION,
	CAUSE_REMOVE_ARMY_ILLEGAL_CELL,
	CAUSE_REMOVE_ARMY_EXPELLED_NO_CITIES,
	CAUSE_REMOVE_ARMY_SCENARIO,
	CAUSE_REMOVE_ARMY_PROBE_RECOVERED,
	CAUSE_REMOVE_ARMY_SINGLE_USE,
	CAUSE_REMOVE_ARMY_ACTIVE_DEFENSE
};

enum CAUSE_NEW_ARMY {
    CAUSE_NEW_ARMY_UNKNOWN,

    CAUSE_NEW_ARMY_INITIAL,

    CAUSE_NEW_ARMY_TRANSPORTED,
    CAUSE_NEW_ARMY_GROUPING,
    CAUSE_NEW_ARMY_UNGROUPING,
	CAUSE_NEW_ARMY_BUILT,
    CAUSE_NEW_ARMY_PARADROP,
    CAUSE_NEW_ARMY_SPACE_LAUNCH,
	CAUSE_NEW_ARMY_UPRISING,
	CAUSE_NEW_ARMY_GOODY_HUT,
    CAUSE_NEW_ARMY_TRADER,
    CAUSE_NEW_ARMY_RUSTLE,
    CAUSE_NEW_ARMY_DIPLOMACY,
	CAUSE_NEW_ARMY_NETWORK,
	CAUSE_NEW_ARMY_CARGO_POD,
	CAUSE_NEW_ARMY_EXPELLED,
	CAUSE_NEW_ARMY_ENTERED_WORMHOLE,
	CAUSE_NEW_ARMY_CHEAT,
	CAUSE_NEW_ARMY_AI_TRANSPORT_CHEAT,
	CAUSE_NEW_ARMY_DISBANDED_CITY,
	CAUSE_NEW_ARMY_SCENARIO,
	CAUSE_NEW_ARMY_UNGROUPING_ORDER,
    CAUSE_NEW_ARMY_REMOTE_GROUPING,
	CAUSE_NEW_ARMY_REMOTE_UNGROUPING,
};


enum CAUSE_REMOVE_CITY {
    CAUSE_REMOVE_CITY_UNKNOWN,
	CAUSE_REMOVE_CITY_FLOOD,
	CAUSE_REMOVE_CITY_HAPPINESS_REVOLT,
    CAUSE_REMOVE_CITY_SLAVE_UPRISING,
    CAUSE_REMOVE_CITY_ATTACK,
    CAUSE_REMOVE_CITY_DIPLOMACY,
	CAUSE_REMOVE_CITY_CHEAT,
	CAUSE_REMOVE_CITY_AI_ENTITY_REVOLT,
};

enum CAUSE_NEW_CITY {
    CAUSE_NEW_CITY_UNKNOWN,
    CAUSE_NEW_CITY_SETTLE,
	CAUSE_NEW_CITY_GOODY_HUT,
	CAUSE_NEW_CITY_REVOLT,
    CAUSE_NEW_CITY_CONQUEST,
	CAUSE_NEW_CITY_SPACE_LADDER,
	CAUSE_NEW_CITY_CHEAT,
	CAUSE_NEW_CITY_DIPLOMACY,
	CAUSE_NEW_CITY_SLAVE_UPRISING,
    CAUSE_NEW_CITY_UPRISING,
	CAUSE_NEW_CITY_INITIAL,
	CAUSE_NEW_CITY_SCENARIO,
};

enum CAUSE_SCI {
    CAUSE_SCI_UNKNOWN,
    CAUSE_SCI_RESEARCH,
    CAUSE_SCI_GOODY,
    CAUSE_SCI_DIPLOMACY,
    CAUSE_SCI_COMBAT,
	CAUSE_SCI_WONDER,
	CAUSE_SCI_CHEAT,
	CAUSE_SCI_INITIAL,
};

enum CAUSE_NEW_PLAYER {
    CAUSE_NEW_PLAYER_REVOLT,
    CAUSE_NEW_PLAYER_NETWORK,
    CAUSE_NEW_PLAYER_UNKNOWN
};

enum ERR_BUILD_INST {
    ERR_BUILD_INST_OK,
    ERR_BUILD_INST_OVERWRITE,
    ERR_BUILD_INST_UPGRADE,
    ERR_BUILD_INST_BLOCKED,
    ERR_BUILD_INST_REDUNDENT
};

enum CAUSE_SPECIAL_ATTACK
{
	CAUSE_SPECIAL_ATTACK_BOMBARD,
	CAUSE_SPECIAL_ATTACK_SUE,
	CAUSE_SPECIAL_ATTACK_SPYING,
	CAUSE_SPECIAL_ATTACK_SLAVERAID,
	CAUSE_SPECIAL_ATTACK_UNDERGROUND_RR_RAID,
	CAUSE_SPECIAL_ATTACK_INCITE_REVOLUTION,
	CAUSE_SPECIAL_ATTACK_STEAL_TECHNOLOGY,
	CAUSE_SPECIAL_ATTACK_INJOIN,
	CAUSE_SPECIAL_ATTACK_ASSISINATE,
	CAUSE_SPECIAL_ATTACK_CONVERT,
	CAUSE_SPECIAL_ATTACK_BIO_INFECT,
	CAUSE_SPECIAL_ATTACK_NANO_INFECT
};

enum CAUSE_HIDDEN_DETECT
{
	CAUSE_HIDDEN_DETECT_MINES,
	CAUSE_HIDDEN_DETECT_STEALTH,
	CAUSE_HIDDEN_DETECT_UNKNOWN
};

#endif // __AI_CAUSE_H__
