








#ifdef HAVE_PRAGMA_ONCE
#pragma once
#endif
#ifndef __LDL_STRINGS_H__
#define __LDL_STRINGS_H__


extern string ID_LOST_BATTLE;
extern string ID_ATTACKED_CIVILIANS;
extern string ID_UNPROVOKED_ATTACK;
extern string ID_ACCIDENTAL_ATTACK;


extern string ID_EXPLAIN_TRADE_CITY_FOR_PEACE;
extern string ID_ADVICE_TRADE_CITY_FOR_PEACE;
extern string ID_NEWS_TRADE_CITY_FOR_PEACE;
extern string ID_EXPLAIN_PEACE_TREATY;
extern string ID_ADVICE_PEACE_TREATY;
extern string ID_NEWS_PEACE_TREATY;
extern string ID_EXPLAIN_THREATEN_ATTACK_CITY;
extern string ID_ADVICE_THREATEN_ATTACK_CITY;
extern string ID_NEWS_THREATEN_ATTACK_CITY;
extern string ID_EXPLAIN_SCENARIO_FORCE_PEACE;
extern string ID_ADVICE_SCENARIO_FORCE_PEACE;
extern string ID_NEWS_SCENARIO_FORCE_PEACE;
extern string ID_EXPLAIN_FEAR_LEAVE_BORDERS;
extern string ID_ADVICE_FEAR_LEAVE_BORDERS;
extern string ID_NEWS_FEAR_LEAVE_BORDERS;
extern string ID_EXPLAIN_BUY_SURPLUS_HARDWARE;
extern string ID_ADVICE_BUY_SURPLUS_HARDWARE;
extern string ID_NEWS_BUY_SURPLUS_HARDWARE;
extern string ID_EXPLAIN_GENERIC_ACCEPT;
extern string ID_ADVICE_GENERIC_ACCEPT;
extern string ID_NEWS_GENERIC_ACCEPT;
extern string ID_EXPLAIN_GENERIC_REJECT;
extern string ID_ADVICE_GENERIC_REJECT;
extern string ID_NEWS_GENERIC_REJECT;
extern string ID_EXPLAIN_CAVE_IN_TO_THREAT;
extern string ID_ADVICE_CAVE_IN_TO_THREAT;
extern string ID_NEWS_CAVE_IN_TO_THREAT;
extern string ID_EXPLAIN_REJECT_THREAT;
extern string ID_ADVICE_REJECT_THREAT;
extern string ID_NEWS_REJECT_THREAT;
extern string ID_EXPLAIN_NO_THREAT;
extern string ID_ADVICE_NO_THREAT;
extern string ID_NEWS_NO_THREAT;
extern string ID_EXPLAIN_REJECT_COUNTER;
extern string ID_ADVICE_REJECT_COUNTER;
extern string ID_NEWS_REJECT_COUNTER;
extern string ID_EXPLAIN_ACCEPT_COUNTER;
extern string ID_ADVICE_ACCEPT_COUNTER;
extern string ID_NEWS_ACCEPT_COUNTER;


extern string ID_SPY_FULL_ATTACK_SS;
extern string ID_ADVICE_FULL_ATTACK_SS;
extern string ID_NEWS_FULL_ATTACK_SS;
extern string ID_SPY_REGROUP_SS;
extern string ID_ADVICE_REGROUP_SS;
extern string ID_NEWS_REGROUP_SS;


extern string ID_SPY_PROVOKE_WAR_DS;
extern string ID_ADVICE_PROVOKE_WAR_DS;
extern string ID_NEWS_PROVOKE_WAR_DS;
extern string ID_SPY_MAKE_FRIEND_DS;
extern string ID_ADVICE_MAKE_FRIEND_DS;
extern string ID_NEWS_MAKE_FRIEND_DS;

#endif __LDL_STRINGS_H__
