#pragma once
#ifndef GLOBALS_H
#define GLOBALS_H 1

#define k_GAME_OBJ_TYPE_UNIT					1
#define k_GAME_OBJ_TYPE_POP						2
#define k_GAME_OBJ_TYPE_IMPROVEMENT				3
#define k_GAME_OBJ_TYPE_TRADE_ROUTE				4
#define k_GAME_OBJ_TYPE_TRADE_OFFER				5
#define k_GAME_OBJ_TYPE_TERRAIN_IMPROVEMENT		6
#define k_GAME_OBJ_TYPE_DIPLOMATIC_REQUEST		7
#define k_GAME_OBJ_TYPE_INSTALLATION			8
#define k_GAME_OBJ_TYPE_WONDER					9
#define k_GAME_OBJ_TYPE_CIVILISATION			10
#define k_GAME_OBJ_TYPE_AGREEMENT				11
#define k_GAME_OBJ_TYPE_MESSAGE					12
#define k_GAME_OBJ_TYPE_ARMY                    13
#define k_GAME_OBJ_TYPE_ENDGAME_OBJECT          14


#define k_GAME_OBJ_TYPE_CAPITALIZATION          16
#define k_GAME_OBJ_TYPE_INFRASTRUCTURE          17

#define k_MAX_ARMY_X 3
#define k_MAX_ARMY_Y 3
#define k_MAX_ARMY_SIZE  (k_MAX_ARMY_X * k_MAX_ARMY_Y)
#define k_MAX_TOTAL_UNITS_IN_CELL (k_MAX_ARMY_SIZE + 1)

#define k_MAX_CIVILISATIONS	64
#define k_MAP_WRAPAROUND 5
#define k_MAX_TEXT_LEN 16384
#define k_MAX_NAME_LEN 512
#define k_NUM_MERIDIANS 6

#define k_MAX_PLAYERS 32

#pragma warning (disable: 4661)


enum WORLD_DIRECTION {
  NORTH,
  NORTHEAST,
  EAST,
  NORTHWEST,
  SOUTHEAST,
  WEST,
  SOUTHWEST,
  SOUTH,
  UP,
  DOWN,
  NOWHERE
};

#define k_MASK_ENV_MOVEMENT_TYPE  0xff000000
#define k_SHIFT_ENV_MOVEMENT_TYPE 24

#define k_MOVEMENT_TYPE_LAND  0x80
#define k_BIT_MOVEMENT_TYPE_LAND (uint32(k_MOVEMENT_TYPE_LAND << k_SHIFT_ENV_MOVEMENT_TYPE))
#define k_MOVEMENT_TYPE_WATER 0x40
#define k_BIT_MOVEMENT_TYPE_WATER  (uint32(k_MOVEMENT_TYPE_WATER << k_SHIFT_ENV_MOVEMENT_TYPE))
#define k_MOVEMENT_TYPE_SPACE 0x20
#define k_BIT_MOVEMENT_TYPE_SPACE  (uint32(k_MOVEMENT_TYPE_SPACE << k_SHIFT_ENV_MOVEMENT_TYPE))
#define k_MOVEMENT_TYPE_AIR 0x10
#define k_BIT_MOVEMENT_TYPE_AIR  (uint32(k_MOVEMENT_TYPE_AIR << k_SHIFT_ENV_MOVEMENT_TYPE))
#define k_MOVEMENT_TYPE_MOUNTAIN 0x08
#define k_BIT_MOVEMENT_TYPE_MOUNTAIN  (uint32(k_MOVEMENT_TYPE_MOUNTAIN << k_SHIFT_ENV_MOVEMENT_TYPE))
#define k_MOVEMENT_TYPE_TRADE 0x04
#define k_BIT_MOVEMENT_TYPE_TRADE (uint32(k_MOVEMENT_TYPE_TRADE << k_SHIFT_ENV_MOVEMENT_TYPE))
#define k_MOVEMENT_TYPE_SHALLOW_WATER 0x02
#define k_BIT_MOVEMENT_TYPE_SHALLOW_WATER (uint32(k_MOVEMENT_TYPE_SHALLOW_WATER << k_SHIFT_ENV_MOVEMENT_TYPE))

#define k_ATTACK_TYPE_UNDERWATER 0x01
#define k_BIT_ATTACK_TYPE_UNDERWATER (uint32(k_ATTACK_TYPE_UNDERWATER << k_SHIFT_ENV_MOVEMENT_TYPE))

#define k_MOVE_ENTER_TRANSPORT_COST 100.0
#define k_MOVE_COMBAT_COST 100.0
#define k_MOVE_AIR_COST 100.0
#define k_MOVE_SPACE_LAUNCH_COST 1000.0

typedef sint32 PLAYER_INDEX;
#define PLAYER_INDEX_VANDALS 0
#define PLAYER_INDEX_0 0
#define PLAYER_INDEX_INVALID 32
#if 0
enum PLAYER_INDEX {
    PLAYER_INDEX_0,
	PLAYER_INDEX_VANDALS = PLAYER_INDEX_0,
    PLAYER_INDEX_1,
    PLAYER_INDEX_2,
    PLAYER_INDEX_3,
    PLAYER_INDEX_4,
    PLAYER_INDEX_5,
    PLAYER_INDEX_6,
    PLAYER_INDEX_7,

    PLAYER_INDEX_8,
    PLAYER_INDEX_9,
    PLAYER_INDEX_10,
    PLAYER_INDEX_11,
    PLAYER_INDEX_12,
    PLAYER_INDEX_13,
    PLAYER_INDEX_14,
    PLAYER_INDEX_15,
    PLAYER_INDEX_16,

    PLAYER_INDEX_17,
    PLAYER_INDEX_18,
    PLAYER_INDEX_19,
    PLAYER_INDEX_20,
    PLAYER_INDEX_21,
    PLAYER_INDEX_22,
    PLAYER_INDEX_23,
    PLAYER_INDEX_24,

    PLAYER_INDEX_25,
    PLAYER_INDEX_26,
    PLAYER_INDEX_27,
    PLAYER_INDEX_28,
    PLAYER_INDEX_29,
    PLAYER_INDEX_30,
    PLAYER_INDEX_31,

    PLAYER_INDEX_INVALID
};
#endif

enum ATTITUDE {
    ATTITUDE_NULL,
    ATTITUDE_HAPPY,
    ATTITUDE_CONTENT,
    ATTITUDE_ANGRY,
    ATTITUDE_NO_EFFECT
};

typedef sint32 PopDBIndex;


enum TERRAIN_TYPES{
TERRAIN_NULL = -10000,
TERRAIN_FOREST =0,
TERRAIN_PLAINS,
TERRAIN_TUNDRA,
TERRAIN_GLACIER,
TERRAIN_GRASSLAND,
TERRAIN_DESERT,
TERRAIN_SWAMP,
TERRAIN_JUNGLE,
TERRAIN_MOUNTAIN,
TERRAIN_HILL,
TERRAIN_WATER_SHALLOW,
TERRAIN_WATER_DEEP,
TERRAIN_WATER_VOLCANO,
TERRAIN_SPACE,
TERRAIN_WATER_BEACH,
TERRAIN_WATER_SHELF,
TERRAIN_WATER_TRENCH,
TERRAIN_WATER_RIFT,
TERRAIN_DEAD,
TERRAIN_BROWN_HILL,
TERRAIN_BROWN_MOUNTAIN,
TERRAIN_WHITE_HILL,
TERRAIN_WHITE_MOUNTAIN,
TERRAIN_DEAD_HILL,
TERRAIN_MAX,
TERRAIN_UNEXPLORED = 31
};

#define k_BASE_TERRAIN_TYPES (TERRAIN_MAX)

typedef sint32 StringId;

enum ROUTE_TYPE {
	ROUTE_TYPE_RESOURCE,
	ROUTE_TYPE_FOOD,
	ROUTE_TYPE_GOLD,
	ROUTE_TYPE_SLAVE,
};

enum MAPSIZE {
	MAPSIZE_SMALL,
	MAPSIZE_MEDIUM,
	MAPSIZE_LARGE,
	MAPSIZE_GIGANTIC
};

#define k_NUM_CITY_TILES 20
#define GROUND_Z 0
#define SPACE_Z 1

#endif
