#pragma once
#ifndef __IMPROVEMENTTYPES_H__
#define __IMPROVEMENTTYPES_H__

enum TERRAIN_IMPROVEMENT
{
	TERRAIN_IMPROVEMENT_IRRIGATION_1,
	TERRAIN_IMPROVEMENT_IRRIGATION_2,
	TERRAIN_IMPROVEMENT_IRRIGATION_3,

	TERRAIN_IMPROVEMENT_ROAD_1,
	TERRAIN_IMPROVEMENT_ROAD_2,
	TERRAIN_IMPROVEMENT_ROAD_3,

	TERRAIN_IMPROVEMENT_MINE_1,
	TERRAIN_IMPROVEMENT_MINE_2,
	TERRAIN_IMPROVEMENT_MINE_3,

	TERRAIN_IMPROVEMENT_CANAL_TUNNEL,

	TERRAIN_IMPROVEMENT_TRANSFORM,
	TERRAIN_IMPROVEMENT_INSTALLATION
};

#endif
