












#pragma once
#ifndef __ORDER_H__
#define __ORDER_H__

enum UNIT_ORDER_TYPE {
	
	UNIT_ORDER_NONE,
	UNIT_ORDER_MOVE,
	UNIT_ORDER_PATROL,
	UNIT_ORDER_CIRCULAR_PATROL,
	UNIT_ORDER_ENTRENCH,
	UNIT_ORDER_SLEEP,
	UNIT_ORDER_DETRENCH,
	UNIT_ORDER_UNLOAD,
	UNIT_ORDER_MOVE_TO_THEN_UNLOAD_THEN_DIE,
	UNIT_ORDER_MOVE_TO,

	
	UNIT_ORDER_TELEPORT_TO,
	UNIT_ORDER_EXPEL_TO,
	UNIT_ORDER_GROUP,
	UNIT_ORDER_UNGROUP,
	UNIT_ORDER_PARADROP,
	UNIT_ORDER_LAUNCH,
	UNIT_ORDER_INVESTIGATE_CITY,
	UNIT_ORDER_NULLIFY_WALLS,
	UNIT_ORDER_STEAL_TECHNOLOGY,
	UNIT_ORDER_INCITE_REVOLUTION,

	
	UNIT_ORDER_ASSASSINATE,
	UNIT_ORDER_INVESTIGATE_READINESS,
	UNIT_ORDER_BOMBARD,
	UNIT_ORDER_SUE,
	UNIT_ORDER_FRANCHISE,
	UNIT_ORDER_SUE_FRANCHISE,
	UNIT_ORDER_EXPEL,
	UNIT_ORDER_ESTABLISH_EMBASSY,
	UNIT_ORDER_CAUSE_UNHAPPINESS,
	UNIT_ORDER_PLANT_NUKE,

	
	UNIT_ORDER_SLAVE_RAID,
	UNIT_ORDER_ENSLAVE_SETTLER,
	UNIT_ORDER_UNDERGROUND_RAILWAY,
	UNIT_ORDER_INCITE_UPRISING,
	UNIT_ORDER_BIO_INFECT,
	UNIT_ORDER_NANO_INFECT,
	UNIT_ORDER_CONVERT,
	UNIT_ORDER_REFORM,
	UNIT_ORDER_INDULGENCE,
	UNIT_ORDER_SOOTHSAY,

	
	UNIT_ORDER_DEFUSE_MINES,
	UNIT_ORDER_CLOAK,
	UNIT_ORDER_UNCLOAK,
	UNIT_ORDER_RUSTLE,
	UNIT_ORDER_CREATE_PARK,
	UNIT_ORDER_CREATE_RIFT,
	UNIT_ORDER_PILLAGE,
	UNIT_ORDER_INJOIN,
	UNIT_ORDER_USE_LADDER,
	UNIT_ORDER_AIRLIFT,
	
	
	UNIT_ORDER_DESCEND,
	UNIT_ORDER_THROW_PARTY,
	UNIT_ORDER_INTERCEPT_TRADE,
	UNIT_ORDER_PARADROP_MOVE,
	UNIT_ORDER_SET_UNLOAD_MOVEMENT_POINTS,
	UNIT_ORDER_GROUP_UNIT,
	UNIT_ORDER_DISBAND,
	UNIT_ORDER_FINISH_ATTACK,
	UNIT_ORDER_UNLOAD_ONE_UNIT,
	UNIT_ORDER_BOARD_TRANSPORT,

	
	UNIT_ORDER_WAKE_UP,
	UNIT_ORDER_PILLAGE_UNCONDITIONALLY,
	UNIT_ORDER_MOVE_THEN_UNLOAD,
	UNIT_ORDER_ADVERTISE,
	UNIT_ORDER_CONDUCT_HIT,

    UNIT_ORDER_INFORM_AI_CAPTURE_CITY, 

	UNIT_ORDER_MAX
};

enum ORDER_RESULT {
	ORDER_RESULT_ILLEGAL,
	ORDER_RESULT_FAILED,
	ORDER_RESULT_SUCCEEDED,
	ORDER_RESULT_INCOMPLETE,
	ORDER_RESULT_SUCCEEDED_INCOMPLETE,
};

struct OrderInfo {
	UNIT_ORDER_TYPE m_type;
	char *m_name;
	sint32 m_goldCost;
	sint32 m_moveCost;
	sint32 m_failSound;
	sint32 m_workSound;
	void *m_userData;
};

#endif
