# Build the Activision classes and native DLL's.
all:
	.\build

# All the .html in this directory is produced by javadoc during build,
# and Activision_anet.h is produced by javah during build,
# so they can and should be deleted when cleaning up.
clean:
	-del *.bat~
	-del *.class
	-del *.c~
	-del *.dll
	-del *.exp
	-del *.h
	-del *.html
	-del *.ilk
	-del *.java~
	-del *.lib
	-del *.obj
	-del *.pdb
	-del log
	-del dlog
	-del log2
	-del dlog2
	-del makefile~
