#ifdef HAVE_PRAGMA_ONCE
#pragma once
#endif
#ifndef __ENDGAMETOKEN_H__
#define __ENDGAMETOKEN_H__

enum TOKEN_ENDGAME {
	TOKEN_ENDGAME_EXACTLY_ONE = TOKEN_MAX + 1,
	TOKEN_ENDGAME_NUM_STAGES,
	TOKEN_ENDGAME_MAX_ALLOWED,
	TOKEN_ENDGAME_TURNS_PER_STAGE,
	TOKEN_ENDGAME_REQUIRED_FOR_STAGE,
	TOKEN_ENDGAME_MIN_REQUIRED,
	TOKEN_ENDGAME_SUCCESS_BONUS,
	TOKEN_ENDGAME_SCORE_BONUS_OVER_MINIMUM,
	TOKEN_ENDGAME_REQUIRES_PROBE_RECOVERY,
	TOKEN_ENDGAME_RUSH_BUY_MODIFIER,
	TOKEN_ENDGAME_CATACLYSM_CHANCE,
	TOKEN_ENDGAME_NOTIFY_LAB_BUILT,
	TOKEN_ENDGAME_STARTS_SEQUENCE,
	TOKEN_ENDGAME_REQUIRES_LAB,
	TOKEN_ENDGAME_SOUND_ID,
	TOKEN_ENDGAME_MAX_VAL
};

	
#endif
