#ifdef HAVE_PRAGMA_ONCE
#pragma once
#endif
#ifndef __GWTOKEN_H__
#define __GWTOKEN_H__

#include "Token.h"
enum TOKEN_POLLUTION
	{
	TOKEN_GLOBAL_WARMING_TRIGGER = TOKEN_MAX + 1,
	TOKEN_GW_POLLUTION_TRIGGER_LEVEL,
	TOKEN_GW_POLLUTION_NEXT_TO_OCEAN,
	TOKEN_GW_POLLUTION_NEIGHBOUR_BONUS,
	TOKEN_GW_POLLUTION_MAX_BONUS,
	TOKEN_GW_POLLUTION_TILE_DESERT,
	TOKEN_GW_POLLUTION_TILE_FOREST,
	TOKEN_GW_POLLUTION_TILE_GLACIER,
	TOKEN_GW_POLLUTION_TILE_GRASSLAND,
	TOKEN_GW_POLLUTION_TILE_HILL,
	TOKEN_GW_POLLUTION_TILE_JUNGLE,
	TOKEN_GW_POLLUTION_TILE_MOUNTAIN,
	TOKEN_GW_POLLUTION_TILE_BROWN_HILL,
	TOKEN_GW_POLLUTION_TILE_BROWN_MOUNTAIN,
	TOKEN_GW_POLLUTION_TILE_WHITE_HILL,
	TOKEN_GW_POLLUTION_TILE_WHITE_MOUNTAIN,
	TOKEN_GW_POLLUTION_TILE_PLAINS,
	TOKEN_GW_POLLUTION_TILE_SWAMP,
	TOKEN_GW_POLLUTION_TILE_TUNDRA,
	TOKEN_GW_POLLUTION_TILE_TO_PLAINS,
	TOKEN_GW_POLLUTION_TILE_TO_JUNGLE,
	TOKEN_GW_POLLUTION_TILE_TO_TUNDRA,
	TOKEN_GW_POLLUTION_TILE_TO_FOREST,
	TOKEN_GW_POLLUTION_TILE_TO_DESERT,
	TOKEN_GW_POLLUTION_TILE_TO_SWAMP,
	TOKEN_GW_POLLUTION_TILE_TO_MOUNTAIN,
	TOKEN_GW_POLLUTION_TILE_TO_BROWN_HILL,
	TOKEN_GW_POLLUTION_TILE_TO_BROWN_MOUNTAIN,
	TOKEN_GW_POLLUTION_TILE_TO_WHITE_HILL,
	TOKEN_GW_POLLUTION_TILE_TO_WHITE_MOUNTAIN,
	TOKEN_GW_POLLUTION_TILE_TO_GRASSLAND,
	TOKEN_GW_POLLUTION_TILE_TO_OCEAN,

    TOKEN_GW_POLLUTION_MAX_VAL
	} ;

#endif
