# Trivial makefile for trivial Java test.
# Use nmake (watcom's make will complain that clean doesn't exist)

test:
	.\test.bat

clean:
	del *.class
	del *.dll
	deltree /y dll
	del makefile~
	del *.java~

